### PR TITLE
Move errant SVG and extract nav links to a partial

### PR DESCRIPTION
**Pull request by mattstauffer**
Note: This only extracts the child links, not the parent; we could make that a separate partial or just keep it in the code like it is now.

### CODE REVIEW

**Comment by reinink** [comment]
Real interesting. Almost makes me think we should go full on and do this for the entire nav. Ie. One big data structure. Was there a reason you didn't do that?

**Comment by mattstauffer** [comment]
@reinink I'd love to!! just didn't want to go overboard :) If y'all are up for it I will

**Comment by reinink** [comment]
I think it might actually be better that way, so I say go for it! 🏄 

Thanks buddy 😍

**Comment by mattstauffer** [comment]
@reinink OK, ready for review. Thanks!

**Review by reinink — APPROVED** [review]
giphy

**Comment by reinink** [comment]
Hmm, I think we lost at least three pages in the nav:

- Border Radius
- Container
- Display

**Review by reinink — CHANGES_REQUESTED** [review]
Need to add back in missing pages 😂

**Comment by mattstauffer** [comment]
@reinink brought back--thanks for catching! 😳

**Comment by reinink** [comment]
YOU ROCK @mattstauffer

**Review by reinink — APPROVED** [review]

**Pull request merged**
