### PR TITLE
Feature/add facebook meta tags

### PR DESCRIPTION
**Pull request by christophrumpel**
Hey Adam,

like requested on Twitter here is the PR :-)

This PR adds the Facebook Open Graph Meta Tags to the site. This way the right content will be shown when the site is shared on Facebook. I have used the given Twitter Card image. Please change it if you want to use another image.

Greets

### CODE REVIEW

**Comment by reinink** [comment]
Does it make sense to have a more dynamic title and description, like we've done for the Twitter meta tags?

**Comment by christophrumpel** [comment]
Yeah you're right. I'll add it. 👍

**Comment by reinink** [comment]
Thanks Chris! 🎉

**Comment by reinink** [comment]
Hmmm, grim, I don't think this got added to the home page. Might have to also update the master layout. Feel liek it Chris? :)

**Pull request merged**
