### PR TITLE
Remove IE11 compatibility code and `target` feature 

### PR DESCRIPTION
**Pull request by adamwathan**
This PR (targeting v2.0) drops any deliberate compatibility with IE11. Anyone who still needs IE11 support can use v1.x, which is still awesome (and the only version that even exists currently! 😋 )

This includes:

- Removing the `target` feature, which was always semi-experimental and never documented
- Removing fallback colors, which drastically reduces CSS file size (now we just ship the `rgba` values, no fallback duplicate declaration in hex)
- Removing the IE11-compatible versions of the transform/rotate/scale/skew/translate utilities

In a future PR I'll be updating our preflight styles to remove IE 10/11 fixes.

### CODE REVIEW

**Comment by SjorsO** [comment]
A lot of the projects I work on need IE11 support because our customer's customers need it. That won't change any time soon. Being stuck on Tailwind 1.0 will be a bummer when there's already a version 2.0 (and later 3.0, 4.0, 5.0...). I think most companies using Tailwind for B2B software are in the same boat.

**Comment by adamwathan** [comment]
What's wrong with Tailwind 1.0 for you currently that will push you to need 2.0?

**Comment by SjorsO** [comment]
> What's wrong with Tailwind 1.0 for you currently that will push you to need 2.0?

I don't necessarily need 2.0, 1.0 already works great. I'm just worried that being a major version behind is going to be a hassle, because it usually is. I'd much rather be on the latest version, but have some core plugins disabled.

**Comment by javascriptjedi** [comment]
I was eager to use the `blocklist` capability in the latest purgecss which isn't available in 1.9.x. My organization is not dropping IE11 for about another year.

**Comment by javascriptjedi** [comment]
There is the workaround provided here at least https://tailwindcss.com/docs/controlling-file-size#setting-up-purge-css-manually.

**Pull request merged**
