### PR TITLE
Sort the theme keys in alphabetical order.

### PR DESCRIPTION
**Pull request by mvdnbrk**

### CODE REVIEW

**Comment by adamwathan** [comment]
Not opposed to sorting all of the core plugin keys alphabetically but I think I'd like to keep screens, colors, and spacing as the first three since they are sort of separate 👍

**Comment by mvdnbrk** [comment]
@adamwathan changed 😄

**Comment by pxwee5** [comment]
Related to https://github.com/tailwindcss/tailwindcss/pull/914

Any reason why we're doing this instead of sorting manually according to css logic? @mvdnbrk ?

For E.g.
Font and Text are logically the same thing and should be close together. But with alphabetical sort they are far apart.

**Comment by mvdnbrk** [comment]
@pxwee5 from the [docs](https://tailwindcss.com/docs/upgrading-to-v1): "_One of the philosophical changes in v1.0 is that we are encouraging people to use their configuration files solely for specifying changes from the default config, rather than including the entire default config plus their changes._"

My thought behind this is that if you want to look up a **default** configuration value from Tailwind it is easier to search for it in a alphabetical order rather than some sort of a css logic.

**Comment by pxwee5** [comment]
Does this mean that our `tailwind.config.js` config is always merged with the `tailwindcss/defaultConfig`? 

And the merge rules are outlined here? 
https://tailwindcss.com/docs/upgrading-to-v1/#2-11-remove-any-configuration-you-havent-customized

**Comment by mvdnbrk** [comment]
@pxwee5 please read the documentation:

_Every section of the config file is optional, so you only have to specify what you'd like to change. Any missing sections will fall back to Tailwind's default configuration._

See [configuration](https://tailwindcss.com/docs/configuration)

**Pull request merged**
