### PR TITLE
Add support for negative css custom properties

### PR DESCRIPTION
**Pull request by tqwewe**
When adding a CSS custom property or `calc()` as a value in a tailwind config, the resulting negative classes are invalid.

For example, adding a custom property to spacing:
```js
const { spacing } = require('tailwindcss/defaultTheme')

{
  theme: {
    spacing: {
      ...spacing,
      foo: 'var(--foo)'
    }
  }
}
```

And the outputted negative margin classes:
```css
.-ml-foo { margin-left: -var(--foo); }
.-mr-foo { margin-right: -var(--foo); }
.-mt-foo { margin-top: -var(--foo); }
.-mb-foo { margin-bottom: -var(--foo); }

.-ml-baz { margin-left: -calc(50% - 10px); }
.-mr-baz { margin-right: -calc(50% - 10px); }
.-mt-baz { margin-top: -calc(50% - 10px); }
.-mb-baz { margin-bottom: -calc(50% - 10px); }
/* ... */
```

This is invalid.
This pull request changes the output to:
```css
.-ml-foo { margin-left: calc(var(--foo) * -1); }
.-mr-foo { margin-right: calc(var(--foo) * -1); }
.-mt-foo { margin-top: calc(var(--foo) * -1); }
.-mb-foo { margin-bottom: calc(var(--foo) * -1); }

.-ml-baz { margin-left: calc(calc(50% - 10px) * -1); }
.-mr-baz { margin-right: calc(calc(50% - 10px) * -1); }
.-mt-baz { margin-top: calc(calc(50% - 10px) * -1); }
.-mb-baz { margin-bottom: calc(calc(50% - 10px) * -1); }
/* ... */
```

This is done by checking if the value starts with `var(` or `calc(` and adjusts the output if true.

### CODE REVIEW

**Comment by adamwathan** [comment]
Thanks! I was able to simplify this and generalize the solution a bit more by using the `reduce-css-calc` library which lets us *always* use `calc(${value} * -1)` to calculate the negative value, since `reduce-css-calc` will reduce the result to a static value if it can 👍 

https://github.com/tailwindcss/tailwindcss/commit/25b3aba7d771b8940c9538425f79b61db705151e

**Comment by mikemand** [comment]
I don't know if it was something I did (or didn't do), but the addition of the `reduce-css-calc` package was causing Laravel Mix to throw this error:

```
ERROR in ./node_modules/reduce-css-calc/dist/parser.js
Module not found: Error: Can't resolve 'fs' in './node_modules/reduce-css-calc/dist'
```

I fixed it by adding:

```
.webpackConfig({
    node: { fs: 'empty' },
})
```

Not sure if there are other solutions, but this one worked for me.

**Comment by schrapel** [comment]
@mikemand Thanks for that fix.

**Comment by MaximVanhove** [comment]
@adamwathan Could we expose the negative helper in css?

So instead of

` margin-left: calc(theme('spacing.12') * -1);`

We could have

` margin-left: negative(theme('spacing.12'));`

**Pull request merged**
