### PR TITLE
Fixed #512: Made @variants respect ::before and ::after pseudo selectors

### LINKED ISSUE #512: @variant with `::before` results in an invalid selector.
Given:

```css
@variant hover {
  .something::before { styles: 'swifty'; }
}
```

The output is:

```
 .hover\:something::before:hover { styles: 'swifty'; }
```

But I'd expect it to be:

```
 .hover\:something:hover::before { styles: 'swifty'; }
```

### PR DESCRIPTION
**Pull request by frankdejonge**
Context in #512

### CODE REVIEW

**Comment by frankdejonge** [comment]
After creating this I realise this is quite opinionated, since it ones intention could also be to provide the pseudo element with a :hover state. It's up to you 🤷‍♂️

**Comment by frankdejonge** [comment]
Right, so there's a very viable alternative for this that works with the current implementation and another postcss plugin. Lemme type up an example.

**Comment by frankdejonge** [comment]
Updated the previous comment to contain the example. Perhaps this should just be added to the docs. Using `postcss-nested` you have all the control you need, the normal `:hover` appending also just works.

Side note, while creating the PR I dug around in the code, was really easy to understand what was going on, so 👍 gud jurb!

**Comment by frankdejonge** [comment]
I celebrated too early. The solution above still produces invalid selectors or at least not selectors you'd expect.

Instead of 

```css
.hover\:something:hover::before { styles: 'swifty'; }
```

You get:

```css
.hover\:something:hover .hover\:::before:hover {

}
```

**Comment by frankdejonge** [comment]
So I did some more digging around, and when postcss encouters the nested rules it will allows you to walk the selectors. This could be by-passed if we detect `&`-rule usage so:

```js
function generatePseudoClassVariant(pseudoClass) {
  return (container, config) => {
    const cloned = container.clone()

    cloned.walkRules(rule => {
      rule.selector = buildPseudoClassVariant(rule.selector, pseudoClass, config.options.separator)
    })

    container.before(cloned.nodes)
  }
}
```

would be replaced by:


```js
function generatePseudoClassVariant(pseudoClass) {
  return (container, config) => {
    const cloned = container.clone()

    cloned.walkRules(rule => {
      if (rule.selector.indexOf('&') !== 0) {
        rule.selector = buildPseudoClassVariant(rule.selector, pseudoClass, config.options.separator)
      }
    })

    container.before(cloned.nodes)
  }
}
```

WDYT, @adamwathan? Sorry for the dump of GH notifications btw 😅

**Comment by adamwathan** [comment]
This one is tricky like you mentioned because it's impossible to know if the end user wants hover applied to the pseudo element or if they want to style the pseudo element when the main element is hovered.

Thinking about this from a different angle, could you solve this same problem using a dedicated variant that you put together using a plugin?

So instead of this:

```css
@variants hover {
  .something::before { styles: 'swifty'; }
}
```

...you'd write something like this:

```css
@variants before-on-hover {
  .something { styles: 'swifty'; }
}
```

...which would generate a class like:

```css
.before-on-hover\:something:hover::before { style: 'swifty'; }
```

Thoughts on that? Can't think of any other way to avoid the ambiguity.

**Comment by adamwathan** [comment]
Going to close this due to lack of activity and the unsolved question around that ambiguity.

**Comment by hacknug** [comment]
Why don't we add hover to the element and introduce a new variant (`hover-pseudo` or similar) in core or as a plugin? Just encountered this issue and I now strongly believe by default we should not add `:hover` to the pseudo-element.

**Pull request closed without merging**
