### PR TITLE
Standardise min/max height/width and width utils

### LINKED ISSUE #5811: Normalize the scales of max width and max height with their width and height counterparts
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/4937

<div type='discussions-op-text'>

<sup>Originally posted by **Soviut** July  9, 2021</sup>
With the advent of JIT mode, it is no longer necessary to save space by having different scales for max width/max height and width/height.

Ideally, I should be able to take any width `w-1/2` and add the `max-` prefix to it without having to consult the documentation.

This could also mean giving `sm`, `md`, `lg`, `xl`, `2xl`, etc. lengths that max-width has to width (and height).</div>

### PR DESCRIPTION
**Pull request by velocity23**
This PR standardizes `max-w-*` and `min-w-*` with `w-` as well as `max-h-*` and `min-h-*` with `h-*`. The idea here is that any value can easily be swapped from `max-w-*` to `w-*` and vice versa and the same with height. This was previous not practical due to file size constraints, but with JIT in v3.0 there's no reason not to do something like this - open to feedback though, of course. There are no breaking changes in this PR, so all existing class names will still work.

I'm aware there's a lot of hard-coded values here that could be extracted to something in the config and I'm happy to work on something like that if that's what the team wants but I thought this might be a good place to start.

Closes #5811

### CODE REVIEW

**Comment by velocity23** [comment]
CC @Soviut

**Review by Soviut — COMMENTED** [review]
I left a few suggestions regarding some missing values. I also discussed the possibility of completely normalizing all the sizes and fractions between height and width.

We'll still need to address testing (which can be a bit painful updating all the test result files).

We'll also need to address documentation changes.

**Comment by Soviut** [comment]
@velocity23 if you don't mind, I'll try adding my suggestions to the PR?

**Comment by adamwathan** [comment]
Will definitely take a look at this more closely soon! Has been on my list as an improvement to make for a while so thanks for getting it started 👍🏻

**Comment by velocity23** [comment]
Thanks Adam! Contributing (and working with @Soviut) has been great fun so let us know if there's anything else we can do.

**Comment by velocity23** [comment]
Sorry for the ping at such a busy time @adamwathan but is there any progress on this?

**Comment by lukewarlow** [comment]
Probably worth rebasing the branch and resolving conflicts before someone looks over it. I believe some of these changes have already been made.

**Comment by Soviut** [comment]
@lukewarlow good call, thanks for pointing that out.

@velocity23 I'll see if I can get that done in the next few days.

**Comment by marco-carvalho** [comment]
looking forward to this PR

**Comment by kyruzic** [comment]
This should really get merged sometime soon. No reason we shouldn't be able to do something like max-h-1/2, but currently we have to manually style or create our own arbitrary values.

**Comment by adamwathan** [comment]
Hey everyone! Still open to doing something like this but the devil is really in the details. I don't like the idea of adding new top-level keys like `fractions` and `sizes` personally, just feels like starting to make a bit of a mess of things.

I don't like the idea of putting it all under `spacing` necessarily either though.

Here's my attempt at an exhaustive list of options, any other ideas?

1. Add new top-level keys like `fractions` and `sizes` to share these values more easily.
2. Add everything under `spacing` so they are automatically shared by anything already using that key.
3. Manually duplicate these values in the places where they make sense to include (similar what we already do for fractional values).

**Comment by Soviut** [comment]
@adamwathan There's also the option of `fractions` and `sizes` being aggregated by `spacing`.

**Comment by ovannavas** [comment]
The class will wrap your image dataset, then when requested, it will return images in batches to the algorithm during training, validation, or evaluation and apply the scaling operations just-in-time. This provides an efficient and convenient approach to scaling image data when modeling with neural networks

**Comment by henial** [comment]
I really appreciated this piece. I often think of how much of a time suck and a mental drain diving into comment conversations can be. But sometimes it is worth it. At the end of the day, it's important to assert oneself and to attempt to have discussions about what matters to you.

**Comment by Soviut** [comment]
Looks like we're getting comment spam from accounts that joined a few days ago. I'm reporting them.

**Comment by ShaggyDude** [comment]
Plus one from me for 'spacing'. I have used that in projects before tailwind and it works fine as a universal scale.

**Comment by adamwathan** [comment]
Just following up here — even though I agree it would be good to simplify and unify some of these things to make things more consistent, I'm not ready to merge this PR as-is for the reasons I mentioned earlier:

https://github.com/tailwindlabs/tailwindcss/pull/5844#issuecomment-1051140013

In the interest of trying to keep on top of our GitHub issues and PRs, I'm going to close this one just because I don't want to adopt this specific solution. Unfortunately I don't have time to dedicate to thinking through this problem deeply right now and providing any actual recommendations on a way to implement this that I _would_ feel comfortable merging, but I'm happy to look at another PR of course that takes a different approach. If I see something that makes me go "ah yes this is nice and is obviously the way we should do this" then there's a good chance it'll get merged! But also possible that I'm still just not totally ready to commit to it, and still don't have the time to prioritize designing the right solution for this above every other thing on the todo list right now.

Either way I do appreciate the PR! 👊

**Pull request closed without merging**
