### PR TITLE
Implement `filter` helper classes with all methods

### PR DESCRIPTION
**Pull request by iduuck**
See #1880 for feature proposal.

### CODE REVIEW

**Comment by iDuuck** [comment]
Very sad, to not get *any* response here since also one month.. Also for #1880...

**Comment by adamwathan** [comment]
I haven't gone through any issues in a while, unfortunately too busy with actual work right now. I go through these in batches and will get to it soon, please don't take it personally. I work 40 hours per week running an extremely understaffed company and have no spare time at all because I'm the father of a two year old.

**Comment by iDuuck** [comment]
@adamwathan I am sorry, didn't knew this! Thanks for the reply, though!

**Comment by joshxyzhimself** [comment]
man this looks lit

**Comment by adamwathan** [comment]
Just an update, I'd like to review this eventually but adding filter support is a big thing and requires a lot of hard thinking about the exact API we expose, what values we expose for each property, etc. so please don't take it personally if I can't dedicate the time needed to properly consider this for a couple of months. Getting support for this into Tailwind will be a couple of weeks of work to make sure we are 100% happy with the APIs, create all of the new documentation pages, come up with good examples for all the docs, etc. So I will need to schedule this into our project calendar in order to give it the attention it deserves.

Thanks again for opening it and looking forward to getting this into the framework in the near future!

**Comment by Chaphasilor** [comment]
Just bumping this so that @adamwathan has to think about if `@tailwindcss/jit` will make it easier to properly integrate this :P  
No pressure though, just a mental crutch ^^

**Comment by adamwathan** [comment]
Bare with me as I attempt dark arts to merge this to a different branch so I can build this feature the way I would want it to work while trying to give you credit for getting it started and not losing your history.

**Comment by adamwathan** [comment]
Alright I've merged this to a new `filters` branch and am going to work on it there. Bunch of things I want to change but I appreciate you getting it started ❤️

**Pull request merged**
