### PR TITLE
Always emit keyframes registered in `addUtilities`

### LINKED ISSUE #14732: v4 alpha 0.28 breaks plugin (tailwindcss-animate) & weird behavior with new p3 color opacity
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.28

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.47, Next.js 15.0.0-rc.1

**What version of Node.js are you using?**

v20.16.0

**What browser are you using?**

Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://github.com/ajayvignesh01/tailwind-v4.0.0-alpha.28-plugins

**Describe your issue**

The `tailwindcss-animate` plugin was working since plugin support landed a few weeks ago. But when I upgrade to alpha 0.28, it stops working. No errors are thrown, but animations that rendered with alpha 0.21 - 0.27 are now not rendering.

Another bug is from the introduction of p3 colors. If you hover over the primary button which has `bg-primary hover:bg-primary/90`, the hover color shows a hue of green for some reason.

Preview with alpha 0.27 - https://tailwind-v4-0-0-alpha-28-plugins-gjaplla02.vercel.app/
Preview with alpha 0.28 - https://tailwind-v4-0-0-alpha-28-plugins-4pzuz8jxf.vercel.app/

### PR DESCRIPTION
**Pull request by thecrypticace**
Fixes #14732

cc @philipp-spiess this look like an okay fix?

### CODE REVIEW

**Comment by adamwathan** [comment]
Wonder if all we actually need to do is revert this one line change?

https://github.com/tailwindlabs/tailwindcss/pull/14672/files#diff-5558c180ba5a080e430ff267430cee62a03a9deedf65a6e8fb5d7c685813c88f

Do `@keyframes` added this way even need to be registered with the theme at all or should we just add them as static CSS rules? The latter sounds more right to me without getting too deep into it.

**Comment by philipp-spiess** [comment]
Ahhh... of course. 🤕  We should probably add a test in the plugin-api spec for this that only uses `addBase` in a plugin and ensures the keyframe is emitted? 

I’m with @adamwathan here in that this feels like it should go directly in the CSS. This way we can also keep the core layer pristine.

**Comment by thecrypticace** [comment]
Ah yeah directly inserting into the AST seems more reasonable. I'll make that change. Ditto w/ addBase + tests

**Review by philipp-spiess — APPROVED** [review]

**Comment by philipp-spiess** [comment]
### Merge activity

* **Oct 22, 12:07 PM EDT**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=tailwindlabs&repo=tailwindcss) once it meets the requirements.

**Pull request merged**
