### PR TITLE
Update defaultConfig.stub.js

### PR DESCRIPTION
**Pull request by kevinruscoe**
The serif array seems to be on a single line whereas every other array is multiline, this just adds consistency.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@kevinruscoe Prettier is formatting it like that

**Comment by kevinruscoe** [comment]
Ah, in that case should "printWidth" be lower? The actual prettier docs says "For readability we recommend against using more than 80 characters".

**Comment by adamwathan** [comment]
I find 80 too low personally, but I’m cool with this change in general,
just not sure how we can prevent Prettier from “fixing” it all the time
without lowering the line length across the board, which results in some
really nasty looking code.

**Comment by MattStypa** [comment]
it looks like `.prettierignore` could be used to ignore the stubs. We already do it for eslint

**Comment by kevinruscoe** [comment]
Yeah, either using `.prettierignore` to globally ignore it, or using inline comments `// prettier-ignore`

**Comment by adamwathan** [comment]
Looks like the stubs are already ignored in our `.eslintignore` so just killed the `.prettierignore` file and merged, thanks!

**Pull request merged**
