### PR TITLE
Allow plugins to add their own config file to be resolved with the user's custom config

### PR DESCRIPTION
**Pull request by adamwathan**
This PR makes it possible for third-party plugins to provide a config object in the same format as Tailwind's regular config object that will be intelligently merged with the user's config as part of the config resolution process.

This is useful when a plugin is adding new utilities and wants to provide default theme values for those utilities that the user can still override or extend the same way they would built-in utilities in Tailwind.

To understand why this is helpful, consider this hypothetical `@tailwindcss/rotate` plugin:

```js
// plugin.js
module.exports = function ({ addUtilities, theme, variants }) {
  const rotateConfig = theme('rotate', {
    '0': '0deg',
    '90': '90deg',
    '180': '180deg',
    '270': '270deg',
  })

  const rotateUtilities = /* ... */

  addUtilities(rotateUtilities, variants('rotate'))
}
```

It looks in the user's config for a `rotate` key, and if not present, provides four default rotate values.

Now consider this Tailwind config file that uses this plugin:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      rotate: {
        '45': '45deg'
      }
    }
  },
  plugins: [
    require('@tailwindcss/rotate')
  ]
}
```

You might think that because the user has specified the new `45` value in the `extend` section, this would add the `rotate-45` utility in addition to the default utilities provided by the plugin, **but it doesn't**. Instead, the `rotate-45` utility is the only one generated, because the `theme()` function exposed to plugins only allows a plugin author to check for the presence of a key and provide a default if the key isn't there.

This PR fixes this problem by allowing plugins to provide a configuration object that Tailwind should intelligently merge into the final config representation, _before_ plugins are properly processed so that features like `extend` work as you might expect even with custom theme keys depended on by plugins.

This is made possible by allowing plugins to now be represented as _objects_ in addition to functions, where the object can have a `config` key, and a `handler` key, which is where you'd put the code you'd normally put directly in the plugin function

For example, here's a plugin that adds `rotate` utilities:

```js
// rotate-plugin.js
module.exports = {
  config: {
    theme: {
      rotate: {
        '0': '0deg',
        '90': '90deg',
        '180': '180deg',
        '270': '270deg',
      },
    },
    variants: {
      rotate: ['responsive']
    }
  },
  handler({ addUtilities, theme, variants, e }) {
    const rotateUtilities = Object.entries(theme('rotate')).map(([key, value]) => {
      return {
        [`.${e(`rotate-${key}`)}`]: {
          transform: `rotate(${value})`,
        },
      }
    })
    addUtilities(rotateUtilities, variants('rotate'))
  }
}
```

By using this new feature and writing this plugin this way, the user can extend or override the default rotate values just like they can with Tailwind's default config:

**Override the defaults**

```js
// tailwind.config.js
module.exports = {
  theme: {
    rotate: {
      quarter: '90deg'
      half: '180deg'
    }
  },
  plugins: [
    require('@tailwindcss/rotate')
  ]
}
```

**Extend the defaults**

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      rotate: {
        '45': '45deg'
      }
    }
  },
  plugins: [
    require('@tailwindcss/rotate')
  ]
}
```

This was implemented by making it possible for Tailwind to resolve multiple config objects under the hood, which is now also exposed to userland in the `resolveConfig` function.

Config objects need to passed in to the `resolveConfig` function starting with the highest priority config, and ending with the lowest priority:

```js
const finalConfig = resolveConfig(mostImportantConfig, nextImportantConfig, lastImportandConfig)
```

In the `resolveConfig` function available by importing `tailwindcss/resolveConfig`, the default config object is always added to the end of the list. Eventually you will be able to override this, likely using a new `extends` property or similar directly in your config where you can specify which configs your config should extend.

### CODE REVIEW

**Comment by adamwathan** [comment]
This is now available to preview in `1.2.0-canary.0`, which you can install using `npm install tailwindcss@canary` or `yarn add tailwindcss@canary`.

**Comment by brandonpittman** [comment]
Having these issues:

- Canary is making builds really slow.
- When plugins used make direct requires of 'postcss', builds **never** finish.
- When installed globally, gets error about not being able to resolve module "resolve".

**Comment by hacknug** [comment]
`npx tailwind init` works fine for me with or without the `--full` flag when installed on a project. Installing things globablly never sounds like a good idea to me. Maybe that's why your gridsome plugin wasn't working for me? 🤔

**Comment by brandonpittman** [comment]
I purely tried the global install as a sanity check. The current stable release works fine globally.

**Comment by hacknug** [comment]
Issue must be coming from #1072 like I mentioned on Discord. I guess this is [the line causing the issue](https://github.com/tailwindcss/tailwindcss/pull/1072/files#diff-586c99afd1e0313d271cabd7a811ddacR3). That's one of the reasons I don't like `npm` and `yarn`, `pnpm` would've probably catched that the moment that PR was opened if that's the actual issue 😃

**Comment by brandonpittman** [comment]
Did more testing…

I have a plugin that bundles other plugins, which worked fine until now, but doing that breaks everything under the canary version.

If I add them all individually in `tailwind.config.js`, then the build speeds aren't bad.

**Comment by adamwathan** [comment]
Can you create a GitHub repo similar to your project that I can use to test performance and try and solve it?

**Comment by brandonpittman** [comment]
I tried a fresh project on a slightly faster Mac, and the speed improved, even with them bundled.

The plugin I'm testing with also bundles custom-forms, which requires me to import postcss and pass it in in the require. Directly requiring that postcss makes builds hang indefinitely.

[Fresh install of this starter](https://github.com/brandonpittman/gridsome-starter-default) with canary added will hang—doesn't without canary.

Also, I may be misunderstanding the importing of configs, but I'm trying to add screens to the config. Adding them in an object exporting a config object directly in `tailwind.config.js` works, but not from within the bundling plugin. Would I need to call resolveConfig directly if not passing the object with the config object/handler?

**Comment by adamwathan** [comment]
> Also, I may be misunderstanding the importing of configs, but I'm trying to add screens to the config. Adding them in an object exporting a config object directly in tailwind.config.js works, but not from within the bundling plugin.

Can you show me some example code so I can make sure I'm understanding correctly?

This should work for example:

```js
// tailwind.config.js
module.exports = {
  plugins: [
    {
      config: {
        theme: {
          extend: {
            screens: {
              xxl: '1440px',
            }
          }
        }
      }
    }
  ]
}
```

**Comment by brandonpittman** [comment]
Here's the plugin content:

```javascript
module.exports = {
  config: {
    theme: {
      extend: {
        screens: {
          dark: {raw: '(prefers-color-scheme: dark)'},
          light: {raw: '(prefers-color-scheme: light)'},
        },
      }
    }
  }
}
```

In `tailwind.config.js`, if I require it in the plugins key, the dark and light screens get added. If I require it from inside the bundling plugin, they don't.

**Comment by hacknug** [comment]
Not sure why you need to import `postcss` there, it's not mentioned in [the docs](https://tailwindcss-custom-forms.netlify.com/). Also, that's available in the object the plugins get so you could destructure in case you were going to need it (doubt it).

Have you tried turning this into a Tailwind plugin and use `config.plugins[]` to have all that together in your package?

**Comment by brandonpittman** [comment]
Well, never thought about it, because it's not in the writing plugins docs, but postcss is actually exposed in the Object-o-Crap that gets passed to plugins!

Not sure what you mean about config.plugins[].

**Comment by brandonpittman** [comment]
If postcss is in the bag of crap each plugin gets, what's the point of this snippet requiring it in the docs?

```javascript
const postcss = require('postcss')

module.exports = {
  plugins: [
    function({ addVariant, e }) {
      addVariant('supports-grid', ({ container, separator }) => {
        const supportsRule = postcss.atRule({ name: 'supports', params: '(display: grid)' })
        supportsRule.append(container.nodes)
        container.append(supportsRule)
        supportsRule.walkRules(rule => {
          rule.selector = `.${e(`supports-grid${separator}${rule.selector.slice(1)}`)}`
        })
      })
    }
  ]
}
```

**Comment by brandonpittman** [comment]
Finally got things working like this:

```javascript
module.exports = {
  config: {
    theme: {
      extend: {
        screens: {
          dark: {raw: '(prefers-color-scheme: dark)'},
          light: {raw: '(prefers-color-scheme: light)'},
        },
      }
    }
  },
  handler(bagOfCrap) {
    require("tailwindcss-plugin-animated")(bagOfCrap)
    require("tailwindcss-plugin-transitions")(bagOfCrap)
    require("tailwindcss-plugin-content")(bagOfCrap)
    require("tailwindcss-plugin-aspect")(bagOfCrap)
    require("tailwindcss-plugin-decoration")(bagOfCrap)
    require("@tailwindcss/custom-forms")(bagOfCrap)
  }
}
```

Tried to touch config.plugins[] directly, but that didn't seem to do anything.

**Comment by adamwathan** [comment]
> If postcss is in the bag of crap each plugin gets, what's the point of this snippet requiring it in the docs?

Docs were written before that was added to the BOC.

**Comment by brandonpittman** [comment]
Can we officially get it named bagOfCrap? 😀

**Comment by brandonpittman** [comment]
OK, here's the magic formula…

```javascript
module.exports = {
  ...require("tailwindcss-plugin-prefers-color-scheme"),
  handler(bagOfCrap) {
    require("tailwindcss-plugin-animated")(bagOfCrap)
    require("tailwindcss-plugin-transitions")(bagOfCrap)
    require("tailwindcss-plugin-content")(bagOfCrap)
    require("tailwindcss-plugin-aspect")(bagOfCrap)
    require("tailwindcss-plugin-decoration")(bagOfCrap)
    require("@tailwindcss/custom-forms")(bagOfCrap)
  }
}
```

If you're using the object versions in `tailwind.config.js`, you don't need to care how they come, but if jamming everything into the bag of gimmicks like I am, you'll need to know which plugins you'll have to spread out.

The above totally works, perf not bad. I'm satisfied with this.

**Comment by eduarguz** [comment]
I have been testing this new feature in an existing app and everything is working fine but with a notable performance issue.

tried to demo the issues in this [repository](https://github.com/eduarguz/test-tailwindcss-120/tree/master), `master` branch uses `v1.2.0-canary.0`

**Comment by brandonpittman** [comment]
I can second those slower numbers. The slowdown from each successive plugin is definitely worse than before.

**Comment by adamwathan** [comment]
@brandonpittman @eduarguz 

Just tagged a new canary release that should fix this:

https://github.com/tailwindcss/tailwindcss/pull/1179

Grab v1.2.0-canary.1 and test if you don't mind! Thanks.

**Comment by eduarguz** [comment]
Awesome

Looks fine to me, some stats:

## Dummy app

### Using @latest
- No plugins - Compiled successfully in **7587ms** 
- Custom Forms Plugin - Compiled successfully in **6329ms**

### Using @1.2.0-canary.0
- No plugins - Compiled successfully in **6656ms**
- Custom Forms Plugin - Compiled successfully in **18777ms**

### Using @1.2.0-canary.1
- No plugins - Compiled successfully in **6425ms** 
- Custom Forms Plugin - Compiled successfully in **6776ms** 👍🏻

## My app

### Using @1.2.0-canary.0
- Custom Plugins - Compiled successfully in **137323ms**

### Using @1.2.0-canary.1
- Custom Plugins -  Compiled successfully in **18091ms** ✨


Thank you so much Adam!

**Comment by brandonpittman** [comment]
Just wondering if 1.2 is ever coming out, or the updates here won't be seen until 2.0 in February.

Also, if you try to use @canary without a full-on build pipeline (just npx-ing it, even when installed locally), it can't find the `resolve` module. Installing that module from npm lets you use `npx tailwind build` though.

**Pull request merged**
