### PR TITLE
Accept config as a JS object

### PR DESCRIPTION
**Pull request by benface**
This feature was previously discussed here: https://github.com/tailwindcss/discuss/issues/37

I needed this for a custom gulp build script where the user is able to override parts of the Tailwind config using a JSON file, so the final config is built dynamically rather than contained in a single file. I am not sure if I implemented it properly, as I didn't take the time to go deep in the codebase, but this worked for me and all the tests passed. I'm sorry if I missed anything; if so please let me know. Also I imagine it would be a good idea to add a test for this feature.

### CODE REVIEW

**Comment by benface** [comment]
Hmm, also sorry for the three commits. I pushed each commit immediately after creating it, so I am not sure how I could squash them?

**Comment by phroggyy** [comment]
tailwind's configuration file exports the configuration, why can't you just merge the user config with the exported tailwind setup?

**Comment by benface** [comment]
@phroggyy Yes, I'm doing that. But then there was no way to pass that merged config object to Tailwind, because it only accepted a path to a file. I could write it to a temporary file, but it seems like a better solution to make Tailwind accept either a file or an object.

**Comment by adamwathan** [comment]
Hey @benface any chance you can update this PR or resubmit without the package-lock.json changes?

**Comment by benface** [comment]
Sure thing @adamwathan, done in #508

**Pull request closed without merging**
