### PR TITLE
Expose `context.sortClassList(classes)`

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR will expose `sortClassList` on the context

This function will be used by the `prettier-plugin-tailwindcss` plugin, this way the sorting happens within Tailwind CSS itself adn the `prettier-plugin-tailwindcss` plugin doesn't have to use internal / private APIs.

The signature looks like this:
```ts
function sortClassList(classes: string[]): string[]
```

E.g.:
```js
let sortedClasses = context.sortClassList(['p-1', 'm-1', 'container'])
```

### CODE REVIEW

**Comment by thecrypticace** [comment]
Can you provide details on how it broke?

**Comment by thecrypticace** [comment]
nvm I think I can see the problem 🤦‍♂️

**Comment by dargmuesli** [comment]
Sure, linting fails https://github.com/maevsi/maevsi/runs/5148080329?check_suite_focus=true#step:5:1288

**Comment by thecrypticace** [comment]
Fixed! Just published v3.0.21. We added the prettier plugin for internal usage so our tests are consistent and it was mistakenly put in `dependencies`. Sorry about that and thanks for the report!

**Pull request merged**
