### PR TITLE
Add overflow hidden classes for each axis

### LINKED ISSUE #439: Add overflow-x-hidden and overflow-y-hidden
They're useful because sometimes you want `overflow-x-hidden overflow-y-auto` (the default `overflow-x` when `overflow-y` is set to `auto` is also `auto`).

### PR DESCRIPTION
**Pull request by hacknug**
This PR adds classes to set `overflow: hidden` for each axis independently. Added a the generated CSS to the tests.

Let me know if you want me to do anything else in order to merge this.

Closes #439.

### CODE REVIEW

**Comment by adamwathan** [comment]
Looks great thanks! Made me realize another inconsistency that is maybe worth solving; should we add `overflow-x-visible` and `overflow-y-visible` too?

**Comment by hacknug** [comment]
I guess it would make sense to have it so anyone can use it to reset the value on different breakpoints in case they need it. I can add this tomorrow when I get back to work if you want.

**Comment by hacknug** [comment]
@adamwathan done!

**Comment by adamwathan** [comment]
Thanks!

**Pull request merged**
