### PR TITLE
feat(boxShadow): automatically join arrays

### PR DESCRIPTION
**Pull request by Larsklopstra**
Automatically join arrays if the `boxShadow` value is an array.

## What does it solve

Configuration is a huge thing in Tailwind CSS and there's nothing better than a clean configuration file. Currently you manually have to join the array which adds unnecessary "bloat" to the configuration file. This PR solves it by joining the array if the value is an array.

### Current implementation

```js
boxShadow: {
  default: [
    "0 1px 1px 0 rgba(0, 0, 0, 0.12)",
    "0 2px 4px 0 rgba(0, 0, 0, 0.04)",
    "0 2px 8px 0 rgba(0, 0, 0, 0.02)"
  ].join(", "),
  sm: [
    "0 1px 1px 0 rgba(0, 0, 0, 0.08)",
    "0 2px 3px 0 rgba(0, 0, 0, 0.02)",
    "0 3px 6px 0 rgba(0, 0, 0, 0.01)"
  ].join(", "),
}
```

or

```js
boxShadow: {
  default: "0 1px 1px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.04), 0 2px 8px 0 rgba(0, 0, 0, 0.02)",
  sm: "0 1px 1px 0 rgba(0, 0, 0, 0.08), 0 2px 3px 0 rgba(0, 0, 0, 0.02), 0 3px 6px 0 rgba(0, 0, 0, 0.01)",
}
```

### After PR

```js
boxShadow: {
  default: [
    "0 1px 1px 0 rgba(0, 0, 0, 0.12)",
    "0 2px 4px 0 rgba(0, 0, 0, 0.04)",
    "0 2px 8px 0 rgba(0, 0, 0, 0.02)"
  ],
  sm: [
    "0 1px 1px 0 rgba(0, 0, 0, 0.08)",
    "0 2px 3px 0 rgba(0, 0, 0, 0.02)",
    "0 3px 6px 0 rgba(0, 0, 0, 0.01)"
  ],
}
```

or still

```js
boxShadow: {
  default: "0 1px 1px 0 rgba(0, 0, 0, 0.12), 0 2px 4px 0 rgba(0, 0, 0, 0.04), 0 2px 8px 0 rgba(0, 0, 0, 0.02)",
  sm: "0 1px 1px 0 rgba(0, 0, 0, 0.08), 0 2px 3px 0 rgba(0, 0, 0, 0.02), 0 3px 6px 0 rgba(0, 0, 0, 0.01)",
}
```

### CODE REVIEW

**Comment by m1guelpf** [comment]
Would be awesome to get this for fonts as well

**Comment by Larsklopstra** [comment]
@m1guelpf Looks like that's already a thing :)

https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/fontFamily.js

**Comment by m1guelpf** [comment]
Oh right, yeah, the font issue was on the typography plugin

**Comment by adamwathan** [comment]
Planning to add this but first I need to solve making theme('boxShadow.md') work when using arrays like this. Hoping to get that sorted out really soon.

**Comment by adamwathan** [comment]
Hey! We ended up solving this more universally in a different way, sorry didn't get to merge this 😕 

Here it is though in case you're interested:

https://github.com/tailwindlabs/tailwindcss/commit/e13f083c4bc48bf9870d27c966136a9584943127#diff-037fae6627d5b8b43bf0c39f3fbf7a7e458cf97af56ea2ad7d35129b9f9f0549

Basically we just automatically support arrays for anything where it makes sense now 👍🏻

**Pull request closed without merging**
