### PR TITLE
Improve preflight v3

### PR DESCRIPTION
**Pull request by kripod**
This PR is a less opinionated implementation of #2607, removing:

- `menu` margin and padding resets, as they are not yet widely adopted
- `hr` border reset
- `overflow-wrap: break-word`

And adding:

- `th`, `td` and `legend` padding resets
- `fieldset` and `iframe` border resets
- `border-spacing: 0` to `table` elements
- `th` text alignment inheritance
- `th` and `address` – `font-size`, `font-weight` and `font-style` resets

Additionally, this PR is based upon #2759 to improve compression performance over the wire.

### CODE REVIEW

**Comment by hacknug** [comment]
Can we also add font resets for these elements? Some might not require us to reset all properties but this is short enough for my projects 😄 

```pcss
:matches(small, label, fieldset, legend, input, select, textarea, button) { font: inherit; }
```

**Comment by kripod** [comment]
> Can we also add font resets for these elements? Some might not require us to reset all properties but this is short enough for my projects 😄
> 
> ```postcss
> :matches(small, label, fieldset, legend, input, select, textarea, button) { font: inherit; }
> ```

All the styles with inconsistencies between browsers are reset. Tailwind already seems to do a great job with handling form elements, except for `fieldset`/`legend`.

**Comment by adamwathan** [comment]
Unfortunately this kinda missed the timeframe for BC breaks with v2.0 and I don't think we can make these changes without them being breaking so I'm going to close. We can revisit Preflight improvements for v3 one day down the road 👍🏻

**Comment by kripod** [comment]
@adamwathan I would like this to be considered for v3, as there are some resets which would be useful but aren’t made by Preflight yet.

**Comment by hacknug** [comment]
Same here. I was thinking of mentioning on Adam's v3 tweet from yesterday but thought it was better not to add more random noise over there. `text-align` and `text-transform` should also be inherited imho.

Would also love to hear from other folks like @benface the same way we did for v1. Sharing our extra reset/normalizer was super helpful for me and resulted in an infinitely superior preflight compared to v0 (expected given the framework's maturity at that point).

Here's some of the resets I have in most projects:

```pcss
@layer base {
  html { scroll-behavior: smooth; }
  svg { @apply fill-current; }

  :matches(label, fieldset, legend, input, select, textarea, button, address, small) {
    font: inherit;
    text-align: inherit;
    text-transform: inherit;
  }
}
```

**Comment by kripod** [comment]
Most of my improvement proposals originate from [css-homogenizer](https://github.com/kripod/css-homogenizer), a modern CSS reset written from scratch by comparing major browsers’ UA stylesheets line by line.

**Comment by benface** [comment]
@hacknug – Thanks for tagging me here. :) I am very interested in any addition or change that improves the DX of Tailwind out of the box, but I must admit I haven't kept up-to-date with the latest Preflight / `modern-normalize` changes.

I agree with the rules you posted. Why not throw in `letter-spacing: inherit` as well, since you have `text-align` and `text-transform`?

I came across @sandren's reset a few months back, and I think there are some great ideas in there too: https://gist.github.com/sandren/386527f13b878d9789400b363f1b865e

**Comment by kripod** [comment]
I would also like to suggest adding the following rule, as inspired by the [CSS Remedy](https://github.com/jensimmons/cssremedy) project:

```css
pre {
  white-space: pre-wrap; /* Overflow by default is bad */
}
```

**Pull request closed without merging**
