### PR TITLE
Add CSS Columns Specification [WIP]

### PR DESCRIPTION
**Pull request by codytooker**
This PR adds a handful of new utilities covering the css column spec.  This is a work in progress and just a proposal on what utilities could be added to cover css columns.

**Added Utilities For**

-  Column Count
-  Column Fill
-  Column Span
-  Column Width
-  Column Rule Width
-  Column Rule Style
-  Column Rule Color

As of now these are all separated into their own generators but can easily be converted into one generator to clean it up.

**Config Updates**

There are some updates to the default config for column-count, column-width, column-rule-wdith, and column-rule-colors, however all of these except for column count could theoretically pull from other config options.  The three column rule specifications are essentially the same as border so we could use those same settings.  Column Width could pull from the width settings as well.

As Css columns is not the most commonly used system in css these generators could be set to false in the default config, but I do think they are useful for their purpose and can be useful in the Tailwind Core.

**Progrees**

- [x] Generators
- [x] Config
- [ ] Docs
- [x] Testing / Fixtures

**Topics of Discussion**

- Converting generators to one simple generator
- Using already established border config settings for the three Column Rule classes
- Default variants or false

### CODE REVIEW

**Comment by codytooker** [comment]
Updated all classes to use `.col-` instead of `.column`

**Comment by adamwathan** [comment]
Hey really sorry to not have addressed this at all until now but I think this would be better suited for a plugin right now. Really appreciate the contribution either way and sorry again for not acknowledging the PR sooner.

**Comment by codytooker** [comment]
Definitely. After building 20 or so sites with tailwind I only used this once.  So a plug-in is definitely a better fit.

**Comment by hacknug** [comment]
I published a plugin while ago inspired by your comments on #540. Links just for reference, in case someone lands here and doesn't look into the related issues:
- https://www.npmjs.com/package/tailwindcss-multi-column
- https://www.npmjs.com/package/tailwindcss-break

**Pull request closed without merging**
