### PR TITLE
Add small-caps to Style & Decoration

### PR DESCRIPTION
**Pull request by XavRsl**
Hi !
I realize just now I haven't created an issue to first discuss this PR, but I would consider it still a "fun experience" to see that PR refused. Anyway, here's my suggestion for adding small-caps and all-small-caps to the Style & Decoration section.

Thanks for your great work guys !

Xavier

### CODE REVIEW

**Comment by damusix** [comment]
Xav, was just doing this and noticed that I needed to update `__tests___/fixtures/tailwind-output.css` in order for tests to pass sanity checks in Travis CI.

https://github.com/tailwindcss/tailwindcss/pull/168/files

**Comment by adamwathan** [comment]
Hey @XavRsl thanks for the PR! We are going to say no to including this in core for now, but of course it's very easy to include these in your own project.

**Comment by XavRsl** [comment]
Thanks. It was fun trying to contribute anyway. Keep up with the great work !!! Helped me get this page up and running in no time:

[pubpeer-dashboard](https://pubpeer.com/journal-dashboard)

**Comment by MichaelDeBoey** [comment]
@XavRsl Is it me or do I recognize the logo from somewhere...? 😉

**Comment by adamwathan** [comment]
@XavRsl That looks great man!

**Comment by XavRsl** [comment]
@MichaelDeBoey I didn't design the logo... Where did you see it?

**Comment by MichaelDeBoey** [comment]
@XavRsl Didn't want to offense you or something, just looked a bit like the @kitetail logo that's all 🙂

**Comment by XavRsl** [comment]
You're not offending anyone. As I told you I didn't make this logo and it was created in january, probably before kitetail's logo. And I don't really find it so similar 🤔

**Comment by MichaelDeBoey** [comment]
@XavRsl It's more similar to an earlier version of the @kitetail logo
Just was the first thing that came to mind that's all 🙂

**Pull request closed without merging**
