### PR TITLE
Modernize codebase

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Since we're targeting `node@>=8.9.0`, I thought it would  be a good idea to modernize the codebase and start using arrow functions and implicit returns where possible.

If this PR gets accepted/merged I'm willing to look into the `lodash` use and convert them to ES6+.

Should be merged after #855, since it's using Prettier already.

### CODE REVIEW

**Comment by adamwathan** [comment]
We were actually already transpiling everything so all of the current decisions about when to use arrows vs. named functions and explicit vs. implicit returns are actually intentional 😬 I think there are some places where the changes in this PR feel like an improvement but not all so not really sure what to do here.

**Comment by MichaelDeBoey** [comment]
It's very inconsistent right now, so just like with Prettier I just wanted to make things more steamlined where possible.

**Comment by MichaelDeBoey** [comment]
All my changes are more with newcomers to the project in mind.
They don't have to think about when to use what, they can just look somewhere else and write the code in a similar way.

Make the step to contributing awesome thing smaller.

**Comment by adamwathan** [comment]
Going to say no to this for now, I think a lot of the changes introduced by Prettier after converting everything to arrow functions with implicit returns makes the code harder to read. For example, I don't like when an implicit return is on it's own line:

```diff
- export default function run(cliArgs) {
-   return new Promise((resolve, reject) => {
+ export default cliArgs =>
+   new Promise((resolve, reject) => {
```

I'd rather use an explicit return if the code can't fit on the same line, and that's one of those code style things Prettier won't handle that I have to do manually.

**Pull request closed without merging**
