### PR TITLE
Hide skipped tests

### PR DESCRIPTION
**Pull request by RobinMalfait**
Very small quality of life improvement, but let's hide skipped tests. The summary still shows that there are skipped tests, but this makes the UI much better. Especially when debugging a single test, then you don't need to scroll up all the time.

### CODE REVIEW

**Comment by RobinMalfait** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14766?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14766** <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14766?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#14765** <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `next`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RobinMalfait and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by thecrypticace — APPROVED** [review]

**Comment by thecrypticace** [comment]
This one makes me happy 🥳

**Comment by adamwathan** [comment]
Does this one actually need to be part of the `@media` refactoring stack or can we just merge this one?

**Comment by RobinMalfait** [comment]
@adamwathan can definitely be a separate PR that doesn't need to be part of the stack. In fact, we can just merge this one.

Reason it is part of the stack is because I changed this code while working on #14767, but didn't want to include it in that PR so created a separate branch from it.

**Pull request merged**
