### PR TITLE
feat: Compatible with applet rpx

### PR DESCRIPTION
**Pull request by Simon-He95**
#11090

### CODE REVIEW

**Comment by xiBread** [comment]
`rpx` isn't a standard CSS unit. You can just do `text-[length:24rpx]` or `[font-size:24px]`.

**Comment by RobinMalfait** [comment]
Hey, thanks so much for this contribution! 🙏

I'm going to say no for now because as @xiBread mentioned the `rpx` unit isn't a standard CSS unit. Luckily there is a workaround by forcing the current type for the arbitrary values:

```html
<div class="text-[length:123px]"></div>
```

We will revisit this if more people want this feature out of the box or if CSS makes it a recognized length unit.

Thanks!

**Comment by Simon-He95** [comment]
All right, thanks for your reply. I will do it in [vscode-tailwind-magic](https://github.com/Simon-He95/vscode-tailwind-magic), text-123rpx -> text-[length:123rpx]

屏幕录制2023-08-11 00 10 44

**Comment by Simon-He95** [comment]
Hi，@RobinMalfait, by the way, Do you think this plugin can be linked to the homepage of tailwindcss, I think it will help people who use tailwindcss

**Pull request closed without merging**
