### PR TITLE
Add ellipsis and no-ellipsis utilities

### LINKED ISSUE #377: [Feature Proposal] Add new "ellipsis" utility
I know there is a `truncate` utility:

```css
.truncate {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

But I suggest adding an `ellipsis` utility that doesn't truncate unless absolutely necessary (when the text cannot wrap anymore):

```css
.ellipsis {
    overflow: hidden;
    text-overflow: ellipsis;
}
```

### PR DESCRIPTION
**Pull request by benface**
Resolves #377

### CODE REVIEW

**Comment by adamwathan** [comment]
I think this is probably good, my only hesitation is around whether or not we should be future proofing to support `text-overflow: <string>` or `text-overflow: fade`. Any thoughts?

**Comment by pnadon** [comment]
I am also interested in this issue, I find that I need to truncate long segments of text, which should still fill their container and not just truncate at the end of the first line.

**Comment by benface** [comment]
@adamwathan Yeah, I don't know. I was under the impression that those would not be available in browsers anytime soon, but I could be wrong. I can change this PR to use the utility names `text-overflow-ellipsis` and `text-overflow-clip` if you prefer that.

@pnadon `text-overflow` only truncates text on a per-line basis. I think you are looking for `line-clamp`; someone else made a feature request here: https://github.com/tailwindcss/tailwindcss/issues/1303

**Comment by adamwathan** [comment]
@benface Finally coming back to this, what about `overflow-ellipsis` and `overflow-clip`? Collides with the regular overflow utilities a bit but whatever, people write `text-sm text-black` and don't complain about it.

**Comment by adamwathan** [comment]
Merged this manually on the command line, thanks!

**Comment by benface** [comment]
Oh hey thanks @adamwathan and sorry for not replying to your earlier comment! I was gonna update my PR (I totally agree with `overflow-ellipsis` and `overflow-clip`) but I'm having a busy week...

**Pull request closed without merging**
