### PR TITLE
Test

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by adamwathan** [comment]
This causes the tests to fail because the function returns `undefined` now :) I'm not getting any lint warnings with what's in master right now and the CI status looks ok:

image

**Comment by DanielRuf** [comment]
Did you clone and check out? Also see https://travis-ci.org/tailwindcss/tailwindcss/builds/537588973

**Comment by adamwathan** [comment]
I fixed the code style in this commit:

https://github.com/tailwindcss/tailwindcss/commit/5e7c263e0a4b0e33af6df02e4122c4b9dc70d1ee

This PR breaks Tailwind because of automatic semi-colon insertion, this code:

```js
    return
      postcss([
        postcssNested({
          bubble: ['screen'],
        }),
      ]).process(style, {
        parser: postcssJs,
      }).root.nodes
```

...will always return undefined because it's evaluated like this:

```js
    return;
      postcss([
        postcssNested({
          bubble: ['screen'],
        }),
      ]).process(style, {
        parser: postcssJs,
      }).root.nodes;
```

I'm on commit `ee42b26` locally and `yarn run style` reports no errors for me 🤔

**Comment by adamwathan** [comment]
Running a new build for the master branch right now:

https://travis-ci.org/tailwindcss/tailwindcss/builds/538930343

**Comment by DanielRuf** [comment]
Well, we should tell prettier to ignore some things. Too opinion based what it wants to do.

```diff
-    return postcss([
+    return;
+    postcss([
       postcssNested({
-        bubble: ['screen'],
-      }),
+        bubble: ["screen"]
+      })
     ]).process(style, {
-      parser: postcssJs,
-    }).root.nodes
-  })
+      parser: postcssJs
+    }).root.nodes;
+  });
```

**Comment by DanielRuf** [comment]
But why does it fail locally?

**Comment by adamwathan** [comment]
Not sure, it doesn't fail locally for me. Running `yarn run style` fails for you?

**Comment by DanielRuf** [comment]
Nevermind, it seems to work now. Not sure if there is some issue between npm and Yarn because the scripts use npm and I run `yarn` like you do in the CI. Probably something npm related (caches?).

**Comment by DanielRuf** [comment]
At least I had also issues that files could not be resolved. After some retries and clearing the npm cache it magically worked again.

**Pull request closed without merging**
