### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rouralberto**

### CODE REVIEW

**Comment by adamwathan** [comment]
Very confusing! What are you talking about?

**Comment by roura356a** [comment]
I know this is not the place to say that. But I have no choice. I'm getting Tailwind SPAM in my email from time to time, so please stop whoever is in charge.

**Comment by adamwathan** [comment]
Can you show me an example? Haven't sent any Tailwind related email since October or November. What's are the emails like and what is the "from" address?

**Comment by roura356a** [comment]
I delete all of them automatically, I'll post them next time if happens again.

**Comment by hacknug** [comment]
Maybe he's watching the repo and getting emails for every new issue and post on those?

**Comment by roura356a** [comment]
@hacknug no, it's actual marketing SPAM.

**Pull request closed without merging**
