### PR TITLE
Add grey as an equivalent to gray

### PR DESCRIPTION
**Pull request by nailuj29**
Some people spell gray as grey, so this PR should prevent any confusion

### CODE REVIEW

**Comment by pmonks** [comment]
And by "some people", am I right to assume that you mean "a majority of people who read & write the English language"?  Only around 25% of English speakers on earth spell this word "gray".

**Comment by nailuj29gaming** [comment]
@pmonks yes, you would be correct

**Comment by adamwathan** [comment]
Hey! This significantly increases the file size of Tailwind in development mode, as well as in the CDN build, so not going to merge unfortunately. You can rename gray to grey in your own config file if you want — you're encouraged to name your colors whatever you like.

I chose `gray` because that's how it is spelled in the native CSS APIs, like:

```css
.grayscale {
  filter: grayscale(1)
}
```

**Comment by nailuj29gaming** [comment]
@adamwathan The color grey is spelled both ways in CSS. See this image:
image

**Comment by nailuj29gaming** [comment]
Also, most people will be using something like PurgeCSS in production, so the increase in file size doesn't really matter.

**Comment by nailuj29gaming** [comment]
@adamwathan just tested it, and it only increases the size by .2 megabytes, which isn't much at all. 
image
The top one had no `grey`, and the bottom one did

**Pull request closed without merging**
