### PR TITLE
Replace cosmiconfig with lilconfig

### PR DESCRIPTION
**Pull request by TrySound**
It's already replaced in postcss-load-config

See https://github.com/postcss/postcss-load-config/blob/main/package.json#L26

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey sorry any chance you could rebase this to resolve the conflicts? Then can definitely merge 👍🏻 Thank you!

**Comment by TrySound** [comment]
Hey, will rebase in a couple of hours! Btw having more ideas how to improve install size.

**Comment by bradlc** [comment]
Hey @TrySound, thanks for updating the PR! What's the reason for updating the `postcss` version in `package.json`?

**Comment by thecrypticace** [comment]
it probably happened automatically and wasn't noticed. NPM is doing the same thing for me any time I npm install a new dependency into the tailwindcss repo. I have absolutely no idea why.

**Comment by TrySound** [comment]
yeah, npm does a bad job with lockfiles. Yarn and pnpm are more stable.

**Comment by bradlc** [comment]
Ah I see, all good 👍 Thanks again!

**Comment by MichaelDeBoey** [comment]
@adamwathan @bradlc This would be a breaking change, as files without an extension are now handled differently
https://github.com/antonk52/lilconfig#difference-to-cosmiconfig

Schermafbeelding 2022-03-06 om 22 06 54

**Comment by TrySound** [comment]
[postcss-load-config](https://github.com/postcss/postcss-load-config) migrated in 3.1.

**Comment by MichaelDeBoey** [comment]
@TrySound They provide the `yaml` loaders themselves instead, so for them it's not breaking at all

Since we don't do that in this PR, it's a breaking change for Tailwind

**Pull request merged**
