### PR TITLE
Fix !important selectors not being classified as valid class inside safelist config

### PR DESCRIPTION
**Pull request by akbng**
## This PR resolves issue #9759 

# PR includes 
- add the '!' prefix as a valid class inside safelisting options
- include tests for the same

### CODE REVIEW

**Comment by thecrypticace** [comment]
Hey, thanks for the PR! Could you add an additional check that the regex pattern contains the `!` character anywhere? We're good with adding this but don't want people to pay for the perf penalty of checking basically doubling the generated classes if they don't need them.

**Comment by akbng** [comment]
> Hey, thanks for the PR! Could you add an additional check that the regex pattern contains the `!` character anywhere? We're good with adding this but don't want people to pay for the perf penalty of checking basically doubling the generated classes if they don't need them.

sure I can try that and also saw some failing tests as well - will try to fix them :+1:

**Comment by thecrypticace** [comment]
If you do that you won't need to fix the failing tests :)

**Comment by thecrypticace** [comment]
Actually, I've already got an implementation. Lemme push it

**Comment by akbng** [comment]
Thanks for the help

**Comment by thecrypticace** [comment]
Thank you! 🎉

**Comment by akbng** [comment]
WOW! I didn't expected such fast action

**Pull request merged**
