### PR TITLE
Work on an interactive example editor

### PR DESCRIPTION
**Pull request by jbrooksuk**
Work in progress...

This adds an optional interactive example editor to Tailwind :)

--- 

image

### CODE REVIEW

**Comment by mkarnicki** [comment]
Hey, this is pretty cool! So you want to add interactive editor to all of the examples in the docs? I think that'd be rad.

In case this helps, I created [Tailwind Filddle](https://tailwind.unravel.eu/) for fun a while ago (it's open source). FWIW I used Ace editor (by Cloud9) instead of codemirror. I invite you to a look 🙂. It's not super clean, but if you're not embarrassed with an early version - you released to late haha. Cheers.

**Comment by ZiFFeL1992** [comment]
Try: https://gustscss.com

**Comment by jbrooksuk** [comment]
The idea for this was that it's baked into the examples itself so that you can see what it's doing in realtime :)

**Comment by mkarnicki** [comment]
That is awesome, @jbrooksuk

**Comment by adamwathan** [comment]
I'd still love to incorporate something like this into the docs at some point but since we've moved the docs to their own repo I'm going to close this WIP PR. Thanks @jbrooksuk!

**Pull request closed without merging**
