### PR TITLE
Fix issue where dark mode experiment won't work if user has plugins array in config

### LINKED ISSUE #2319: Tailwindcss v1.8 dark mode (experimental) issue
### Describe the problem:
🚫 Error: Your config mentions the "dark" variant, but "dark" doesn't appear to be a variant. Did you forget or misconfigure a plugin that supplies that variant?

### Link to a minimal reproduction:
```javascript
// tailwind.config.js
'use strict';

module.exports = {
  dark: 'class',
  experimental: 'all',
  future: {
    purgeLayersByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  purge: {
    content: [
      './public/**/*.html',
      './src/**/*.js',
    ],
  },
  theme: {
    extend: {
      colors: {
        'dark-gray': '#121212',
        gray: {
          '100': '#f5f5f5',
          '200': '#eeeeee',
          '300': '#e0e0e0',
          '400': '#bdbdbd',
          '500': '#9e9e9e',
          '600': '#757575',
          '700': '#616161',
          '800': '#424242',
          '900': '#212121',
        },
      },
      cursor: {
        'zoom-in': 'zoom-in',
        'zoom-out': 'zoom-out',
      },
    },
  },
  variants: {},
  plugins: [],
};

```
When run build command `npx tailwindcss build -o src/index.css`, getting the above error.

### PR DESCRIPTION
**Pull request by adamwathan**
Fixes #2319.

### CODE REVIEW

**Comment by brandonpittman** [comment]
@adamwathan I'm guessing this is Tailwind UI's fault, but including the UI plugin kills the `dark` variants. I'm guessing it's because Tailwind UI sets a whole bunch of variants for you. I saw the same issue in my tailwindcss-plugin-fancy plugin where including @tailwindcss/ui overwrote variants I myself was trying to include. I'd be happy to remove the UI plugin, but I'm relying on the colored outline, solid shadow outlines, and the cool-gray colors.

**Comment by codex-zaydek** [comment]
@brandonpittman I ran into the same issue. I can’t easily give up the Tailwind UI plugin right now because I’m relying on too many classes generated by it to simply remove it. That being said, [I found this comment](https://github.com/tailwindlabs/tailwindcss/issues/2319#issuecomment-687635134) to be useful.

Instead of using the experimental dark mode support that (as of 0.8.3 for me) still breaks, this is working as expected and should be easy enough to adapt to a class if needed:

```js
module.exports = {
  // ...
  theme: {
    screens: {
      // ...

      "dark": {
        "raw": "(prefers-color-scheme: dark)",
      },
    },
  },
  // ...
}
```

**Comment by brandonpittman** [comment]
@codex-zaydek I wound up requiring Tailwind UI and just grabbed the boxShadow and color bits I needed.

**Comment by adamwathan** [comment]
@codex-zaydek What error are you seeing when trying to enable dark mode with the Tailwind UI plugin? This builds no problem for me:

```js
module.exports = {
  purge: ['./index.html'],
  future: 'all',
  experimental: 'all',
  plugins: [require('@tailwindcss/ui')],
}
```

**Comment by brandonpittman** [comment]
@adamwathan Tailwind UI overwrites the variants so only colors like placeholder have dark variants. Border Color and background color variants get set in @tailwindcss/UI, so the dark variants never show up.

**Comment by codex-zaydek** [comment]
@adamwathan Hey Adam — try this config:

```js
module.exports = {
  dark: "media",
  experimental: {
    darkModeVariant: true,
  },
  plugins: [
    require("@tailwindcss/ui"),
  ],
}
```

This curiously generated _no_ `bg-*` classes for me. I tried searching using this regex: `\.dark\:bg` and tried using classes like `dark:bg-green-500` but nada.

I’m on `1.8.3tailwindcss@^1.8.3` and `@tailwindcss/ui@^0.5.0` (from yarn.lock). Using the legacy dark mode technique @brandonpittman mentioned still works for me so I’m just using that for now.

**Comment by brandonpittman** [comment]
⬆️ Just as I said.

**Comment by adamwathan** [comment]
Yep yep yep I understand now, thanks! Will try to push out a fix today, will require a new version of the Tailwind UI plugin.

**Comment by codex-zaydek** [comment]
Awesome — thanks! 🔥

**Comment by codex-zaydek** [comment]
Adam this config seems to fix it:

```js
const defaultVariants = require("./tailwind-defaultVariants.1.8.3.js")

module.exports = {
  dark: "class",
  experimental: {
    darkModeVariant: true,
  },
  plugins: [
    require("@tailwindcss/ui"),
  ],
  // https://github.com/tailwindlabs/tailwindcss/releases#dark-mode-experimental
  variants: {
    ...defaultVariants,
    backgroundColor: ({ after }) => after(["dark"]),
    borderColor: ({ after }) => after(["dark"]),
    divideColor: ({ after }) => after(["dark"]),
    gradientColorStops: ({ after }) => after(["dark"]),
    placeholderColor: ({ after }) => after(["dark"]),
    textColor: ({ after }) => after(["dark"]),
  },
}
```

Basically I copied over the default variants and imported them, then for the dark mode variants I added `dark` as an `after` argument.

**Comment by adamwathan** [comment]
Can you guys test out @tailwindcss/ui@0.6.0 and see if it works for you? Should solve this problem, but it's only compatible with Tailwind v1.8+.

**Comment by codex-zaydek** [comment]
Sure. Will test this now! Thank you.

**Comment by codex-zaydek** [comment]
Hey @adamwathan, still broken for my use-case. This is an improvement but it’s not working 100% as expected.

Here is the essence of my working config:

```js
module.exports = {
  dark: "class",
  experimental: {
    darkModeVariant: true,
  },
  plugins: [
    require("@tailwindcss/ui"),
  ],
  variants: {
    opacity: ({ after }) => after(["group-hover", "group-focus"]),
    scale: ({ after }) => after(["group-hover", "group-focus"]),
    textColor: ({ after }) => after(["group-hover", "group-focus"]),
  },
}
```

And my code basically looks like this: `... dark:group-hover:text-purple-50 ...`. So I searched my generated Tailwind CSS file for this regex: `dark\\\:group-hover\\\:text-purple-50` and I got this:

```css
.dark .dark\:group:hover .dark .dark\:group-hover\:text-purple-50 {
  --text-opacity: 1;
  color: #f6f5ff;
  color: rgba(246, 245, 255, var(--text-opacity));
}
```

It looks like this _almost_ works but the presence of the second `.dark` class, before `.dark\:group-hover\:text-purple-50` is probably breaking the selector chain, which no-ops this CSS. I _am_ getting the `dark:bg-*` classes now — thank you, but this is still failing for my `group-hover` CSS. Just to be clear, I’m not getting any warnings.

**Comment by adamwathan** [comment]
Ah this is actually a straight up bug, looks like the dark mode stuff does not play nicely with the `class` strategy at the moment. I'll open an issue for this and work on a fix, thank you!

**Comment by codex-zaydek** [comment]
You bet. Feel free to follow-up with me for testing with a real-world app. 👍

**Comment by brandonpittman** [comment]
@adamwathan @codex-zaydek The @tailwindcss/ui update fixed the issue and the new variant extension feature solved the issue I had with variants and [tailwindcss-plugin-fancy](https://github.com/brandonpittman/tailwindcss-plugin-fancy/releases/tag/2.1.0)! 🌶

**Pull request merged**
