### PR TITLE
Make `decodeArbitraryValue` overridable

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR allows us to override the `decodeArbitraryValue` function used when parsing candidates and variants.

I'm not 100% happy with this (open for suggestions!) but it was either this, or introducing some class where we mock a method or as a last resort, copy the whole `parseCandidate` implementation and make the necessary changes there when running codemods.

While the last one seems to be the cleanest, I'm afraid that the implementation will diverge over time.

### CODE REVIEW

**Comment by RobinMalfait** [comment]
* **#14718** <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14718?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14717** <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `next`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RobinMalfait and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by RobinMalfait** [comment]
* **#14718** <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14718?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#14717** <a href="https://app.graphite.dev/github/pr/tailwindlabs/tailwindcss/14717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `next`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @RobinMalfait and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by philipp-spiess** [comment]
Phew yeah this is ugly. I do think maybe hard-forking `parseCandidate` might actually be easier, even if it means a bit of duplication.

> I'm afraid that the implementation will diverge over time.

@RobinMalfait I wonder if this maybe is simpler in the long term? Assume we add a new feature to the parseVariant, the way we reuse the code means that we now also support this new feature in the v3 => v4 migration where as we never did support this in v3 probably so it's starting to migrate candidates that aren't supposed to be migrated?

It also means we can make changes to the "core" `parseCandidate` without having to worry about breaking our migrator. 🤔

**Comment by adamwathan** [comment]
Going to close this in favor of #14720 — I think that's the cleaner way to approach this problem 👍

**Pull request closed without merging**
