### PR TITLE
Make form elements inherit more font properties

### PR DESCRIPTION
**Pull request by adamwathan**
By default, browsers apply a bunch of default font-related properties to form elements that take precedence over styles defined on the parent element.

Since Tailwind encourages you to implement designs using a constrained system, this can be a bit of a pain point and lead to accidentally leaving in user agent styles that aren't part of your design system, like the text in inputs being full-on black, or buttons having a slightly different line-height than normal text.

Normalize.css (which we use as the base for our Preflight styles) [corrects](https://github.com/necolas/normalize.css/blob/master/normalize.css#L155-L169) a lot of these inconsistencies:

```css
/**
 * 1. Change the font styles in all browsers.
 * 2. Remove the margin in Firefox and Safari.
 */

button,
input,
optgroup,
select,
textarea {
  font-family: inherit; /* 1 */
  font-size: 100%; /* 1 */
  line-height: 1.15; /* 1 */
  margin: 0; /* 2 */
}
```

...but doesn't touch color or font-weight, as that would be a bit too opinionated for what Normalize is trying to do.

This PR makes all form elements inherit `color`, `font-weight`, and `line-height` so that it's much harder to accidentally introduce styles that deviate from your design system.

That way if you don't override any of those values on a form element with a utility, at least the default value will be something specified in your system (assuming you have added some base styles to the `html` or `body` tag).

Put another way, this PR tries to make sure that a form element with a given list of utilities applied to it looks exactly the same as a `span` would look with the same utilities.

### CODE REVIEW

**Comment by benface** [comment]
I'm totally on board, and I would go even further. As it is now, this PR doesn't let form elements inherit the following properties by default (while a `span` would):

- `font-style`
- `font-variant`
- `text-align`
- `letter-spacing`
- `text-transform`

Maybe they're not as important/needed, but IMO we should go all the way or not at all. Note that the first two properties of that list could be taken care of by setting the [`font` shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/font) to `inherit`, but maybe it's better to be explicit?

**Comment by hacknug** [comment]
I checked earlier if any of the stylesheets @CvX shared on #738 were setting `letter-spacing` in any way and it looks like they're not.

I really don't why it was on my reset stylesheet so maybe we don't need all of those?

**Comment by benface** [comment]
We do need them, I tested earlier. Although just to be sure, I tested in other browsers and Firefox seems to inherit some properties on `<button>`s by default, but I'm pretty sure it's a bug because they do it for `text-transform` and `letter-spacing` but not for `font` or `color`...

**Comment by hacknug** [comment]
Perfect. Then imo we should use the explicit properties instead of the shorthand (although I was the one using the `font` on my reset). From experience, shorthands are never a good idea because not everyone know how many nor which properties are being set when using them.

The only issue with not using them _could_ be file size which would not really be an issue after using most CSS minifiers (they use shorthand properties to reduce the ammount of characters in your styles). This could also not be an issue due to string repetition with gzip or brotli compression, so… 🤷‍♂️

**Comment by benface** [comment]
> Then imo we should use the explicit properties instead of the shorthand (although I was the one using the font on my reset). From experience, shorthands are never a good idea because not everyone know how many nor which properties are being set when using them.

Yeah I agree!

**Comment by adamwathan** [comment]
Good suggestions so far, copying over @benface's reset from the other issue too:

```css
 button,
 input,
 textarea,
 select {
     margin: 0;
     padding: 0;
     border-radius: 0; /* for iOS */
     background-color: transparent;
     font: inherit;
     color: inherit;
     text-align: inherit;
     text-transform: inherit;
     letter-spacing: inherit;
 }
```

I think these styles make a lot of sense if we really want buttons and inputs to essentially act like spans (although maybe there's a good argument for why they shouldn't?) Thoughts on moving ahead with this whole reset (but split into individual properties)?

**Comment by adamwathan** [comment]
Just pushed an update with the following reset styles:

```css
button,
input,
optgroup,
select,
textarea {
  padding: 0;
  border-radius: 0;
  background-color: transparent;
  font-weight: inherit;
  line-height: inherit;
  color: inherit;
  font-style: inherit;
  font-variant: inherit;
  text-align: inherit;
  text-transform: inherit;
  letter-spacing: inherit;
}
```

Thoughts @benface and @hacknug?

**Comment by benface** [comment]
@adamwathan I don't understand what styling `optgroup` does, but other than that, looks great!

**Comment by adamwathan** [comment]
After a lot of discussion in Discord and some input from @jackmcdade I've decided to lighten up on this reset a bit and just focus on the things that are actually annoying:

```css
button,
input,
optgroup,
select,
textarea {
  padding: 0;
  line-height: inherit;
  color: inherit;
  background-color: transparent;
}
```

The only property I removed that feels a little iffy is font-weight, as technically now your buttons/inputs could be using a font weight (`normal`/400) that isn't in your design system. I decided I am comfortable with this because anyone intentionally avoiding using the normal font weight for their entire site probably won't be surprised that they have to override that on form elements. They also would have had to do that already for the last 18 months that Tailwind has existed, so whatever, this is still a little more helpful.

**Comment by adamwathan** [comment]
Upon even more thinking, I've decided to remove `background-color: transparent` as it's a bit of an annoying breaking change for anyone who was relying on inputs being white by default, and I don't think it's that unreasonable to have to make an input explicitly transparent when that's the behavior you want.

```diff
  button,
  input,
  optgroup,
  select,
  textarea {
    padding: 0;
    line-height: inherit;
    color: inherit;
-   background-color: transparent;
  }
```

Buttons are still transparent by default thanks to an earlier rule in Preflight, which we will keep because no one ever depends on the default user agent button background color, and it's very common to use a button for something that doesn't have a solid background.

**Pull request merged**
