### PR TITLE
Add z-index negative defaults

### PR DESCRIPTION
**Pull request by the94air**
This should add support for negative z-indexes when using Tailwindcss from a CDN as discussed in #329 with @hacknug.
Should add:
1. `.-z` and it's other breakpoints utilities.
2. `.-z-10` it's other breakpoints utilities.

Thanks.

### CODE REVIEW

**Comment by hacknug** [comment]
I have the feeling Adam will say no to `.-z`, everything else looks good. Let's wait to hear from him 👍

**Comment by adamwathan** [comment]
I feel like I've never needed this, mind sharing a concrete example where it's significantly nicer than trying to solve it with positive z-index values?

**Comment by narwy** [comment]
I guess for pseudo elements and something might already be z-index'd you would want a negative to counter that?, I've seen this used before. Think it could be a good addition.

**Comment by hacknug** [comment]
@adamwathan it helps bringing something behind everything else without touching more than that background element. Something like this I had on a project of mine:

```vue
<div>
  <header class="relative z-10 overflow-hidden bg-green-100 shadow">
    <slot name="head" />
    <div class="absolute inset-x-0 w-full" style="z-index: -10; top: 35%;"></div>
  </header>
  <main class="relative z-0 bg-gray-100">
    <slot name="main" />
  </main>
</div>
```

**Comment by the94air** [comment]
I had the same use case as @hacknug, @adamwathan.

**Comment by timacdonald** [comment]
In the process of rebuilding my site in Tailwind and I ran into a need for this. Think it could be handy if there was a *single* negative z-index.

@adamwathan my use-case was I wanted to preset an image with an inset box shadow over the top of it ([prior art](https://twitter.com/steveschoger/status/1064541476615593984)). There is potentially another way to do this in Tailwind with positive indexes (?), but this was the [quick solution I implemented](https://codepen.io/timacdonald/pen/WNrrxpa?editors=1100) which utilises a single negative z-index.

Not sure if this is a good enough use case to bring this into the core of Tailwind, but I personally would have found a single negative value out of the box handy.

Thanks for Tailwind ❤️

**Pull request closed without merging**
