### PR TITLE
Add support for functions in flattenColorPalette

### PR DESCRIPTION
**Pull request by ivoilic**
Currently flattenColorPalette does not handle values that are functions. This change allows for functions to be be flattened optionally, so it should not break existing setups. This could potentially be further enhanced by then also checking if the function's returned value is an object and flattening that as a well. I also added a simple test for this new functionality.

### CODE REVIEW

**Comment by ivoilic** [comment]
I realize the example in the test is a bit silly. Here is a real world example of the kind of function that this could be used for:
```
function withOpacity(variableName) {
  return (options) => {
    if (options !== undefined && options.opacityValue !== undefined) {
      return `rgb(var(${variableName}) / ${options.opacityValue})`;
    }
    return `rgb(var(${variableName}))`;
  };
}
```

**Comment by adamwathan** [comment]
Hey thanks @ivoilic! Can you share more details about the motivating situation that led you to add this? What problem did you run into with your project that required this change?

We've made a bunch of improvements in the last while to try and avoid anyone ever needing to define colors as functions anymore and don't actually even document it, so just want to make sure this is 100% necessary before deciding to merge it 👍

**Comment by ivoilic** [comment]
@adamwathan for my use case this is no longer needed. I saw the changes in the docs for using css variables with opacity and that's working great for me. Thanks for taking the time to check this out anyways. I'll go ahead and close this PR.

**Comment by adamwathan** [comment]
Ok cool good to know! I'll close this for now then, knowing we can always revisit this later if a use-case pops up for it. Thanks again!

**Pull request closed without merging**
