### PR TITLE
Create backgroundAttachment.js generator

### PR DESCRIPTION
**Pull request by sorinr**
Hi,

Proposed new background-attachment classes

### CODE REVIEW

**Comment by tlgreg** [comment]
With values like `scroll`, `fixed` and `local` its good as its obvious that the utility is for the attachment, but the others are generic values, which can be applied to all of the `background-*` properties.

**Comment by adamwathan** [comment]
I'm not opposed to adding these but I think like @tlgreg mentioned we actually only need `scroll`, `fixed`, and `local`; not enough benefit to the other options IMO.

If you can update the PR to just those three values, I'm ok to merge it as is and update the tests and stuff myself.

**Comment by sorinr** [comment]
Yep. U are both right. I have updated the file to only those 3 values.

**Comment by adamwathan** [comment]
Thanks! I've merged this into a separate branch so I can do the rest of the work necessary to get it into the framework 👍

**Comment by sorinr** [comment]
Keep up the great job guys 👍

**Pull request merged**
