### PR TITLE
Support negative prefix syntax for boxShadow and letterSpacing

### LINKED ISSUE #982: [Feature Request] Support negative prefix syntax in config for letterSpacing and boxShadow
### Background
When I'm using letter spacing utilities, I prefer numerical class names like `tracking-1`, `tracking-2`, etc. instead of `wide`, `wider`, etc. 

I also like to set my negative letter spacing values to `-tracking-1`, `-tracking-2`, etc.—the negative prefix makes it more explicit that I'm shrinking the font's normal letter spacing.

Same goes for box shadows—I prefer `shadow-1`, `shadow-2`, etc., and I dig `-shadow` instead of `shadow-inner`. Also feels cleaner to do something like `-shadow-1`, `-shadow-2`, etc. instead of `shadow-inner-md`, `shadow-inner-lg`, etc.

### Problem

For `zIndex`, `margin`, and `inset`, you can easily create these prefixed classes in your config like so:

```
zIndex: {
  '10': '10', // z-10
  '-10': '-10' // -z-10
}
```

But the negative prefix syntax isn't supported for any other utilities (I edit Tailwind's source code in my projects to get it working).

### Solution

Support negative prefix syntax for `letterSpacing` and `boxShadow`. Looking through the other plugins, it might make sense to add support for `lineHeight` too.

If this is considered a breaking change, it's probably not worth it. Otherwise, I'd be happy to make the pull request.

### PR DESCRIPTION
**Pull request by AlexVipond**
Closes #982 

This PR takes the z-index negative prefix feature and applies it for letter spacing and box shadow. I was also going to support line height, but I discovered that negative line heights are invalid CSS, so I don't think there's a use case for it.

This PR also tweaks the `prefixNegativeModifiers` util so that you can create classes like `-shadow` simply by putting `'-'` as the name of your config key. It's kind of like the `default` keyword, but for negative prefixed classes (see example below).

Here's an example of how it would allow you to configure tailwind (resulting classes are in the comments on each line):

```
// tailwind.config.js

module.exports = {
  theme: {
    lineHeight: {
      '-2': '-0.05em', // -tracking-2
      '-1': '-0.025em', // -tracking-1
    },
    boxShadow: {
      '-': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)', // -shadow
      '-md': 'inset 0 4px 6px 0 rgba(0, 0, 0, 0.10), inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)', // -shadow-md
    }
  }
}
```

**linting note**: linter was telling me not to use nested ternaries in `prefixNegativeModifiers`, I'll refactor that to if/else if it's a problem

### CODE REVIEW

**Comment by adamwathan** [comment]
Thanks Alex! Looks like the tests are failing because `.shadow` has changed to `.shadow-default` by mistake, happy to merge if you don't mind fixing that 👍

**Comment by AlexVipond** [comment]
@adamwathan all set, I fixed that for `boxShadow`, and I tweaked `zIndex` and `letterSpacing` to handle the `default` keyword and the single `'-'` in the same way. People probably won't use `default` or `'-'` on those plugins, but the changes seemed like a good idea for the sake of consistency.

Also added some new tests for those three plugins and for the `prefixNegativeModifiers` util, and fixed formatting errors from prettier.

**Comment by adamwathan** [comment]
> People probably won't use default or '-' on those plugins, but the changes seemed like a good idea for the sake of consistency.

Yeah I originally wanted this to be consistent but then I discovered `.cursor-default` and that ruined everything. Hard to say if that should be an exception or if we should be deliberate about which plugins support `default`. All this stuff is kind of a breaking change (and a bug fix, and a feature addition, all at the same time depending on how you look at it 😜) so have to be a little bit careful.

For now I think I would prefer that we not add the `default` handling to the zIndex and letterSpacing plugins, do you mind reverting that? If not I can do it myself 👍

**Comment by AlexVipond** [comment]
@adamwathan I reverted `default` keyword support for zIndex and letterSpacing

**Comment by adamwathan** [comment]
I'm not totally sure if I prefer `-` or `-default` for utilities like `-shadow` but at the same time there's really no other reasonable behavior `-` can have other than what it does in this PR so I think I'm good with it even if we decided to support `-default` eventually as well. Thanks Alex 👍

**Pull request merged**
