### PR TITLE
Add sticky utility

### PR DESCRIPTION
**Pull request by sebastiandedeyne**
Adds a `.sticky` class for `position: sticky`.

https://developer.mozilla.org/en-US/docs/Web/CSS/position

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Just realised there are larger positioning examples in the docs later on the page. If you guys are interested in merging this I'd be happy to add a a section there too in another commit or follow up PR, let me know!

**Comment by reinink** [comment]
Hey @sebastiandedeyne, thanks for this contribution. One issue is see that sticky doesn't have IE11 browser support, which is a browser we've been trying to support with Tailwind.

image

**Comment by sebastiandedeyne** [comment]
Yeah, can't be solved with pure CSS either... I personally wouldn't mind having utilities that aren't supported everywhere, with a note in the docs where it is or isn't compatible.

I'd totally understand it if you guys think it's a bit early and don't want to deal with stuff like this though, in that case I'll just declare it in my own projects when necessary :)

**Comment by adamwathan** [comment]
Going to close this for now; if we ever add any other utilities by default that don't support IE 11 we can revisit this then. Thanks though!

**Comment by adamwathan** [comment]
Reopening and adding this because position sticky is great, thanks!

**Pull request merged**
