### PR TITLE
compile with swc

### PR DESCRIPTION
**Pull request by sachinraja**
Feel free to close this PR if it is too experimental to use. It switches out babel for [`swc`](https://github.com/swc-project/swc), a super-fast javascript compiler written in rust. Building the repo is 20x faster (123.29ms) compared to babel (2848ms). I realize this is a minimal difference, but it is still faster. SWC is applied to the test ([`@swc/jest`](https://github.com/swc-project/jest)) and script files ([`@swc/register`](https://github.com/swc-project/register)) too.

### Notes
* Next.js recently added support for compiling their [server](https://github.com/vercel/next.js/pull/27167) and [client](https://github.com/vercel/next.js/pull/27196) files.
* [Deno uses swc](https://deno.land/manual@v1.11.3/typescript/overview#how-does-it-work)
* [Parcel's new compiler runs on top of swc](https://v2.parceljs.org/blog/beta3/)

### CODE REVIEW

**Comment by reinink** [comment]
Hey we'd like to merge this, but the tests are currently failing because swc isn't maintaining the export order of our plugins (in [corePlugins.js](https://github.com/tailwindlabs/tailwindcss/blob/master/src/corePlugins.js)). If you can think of a solution for this and want to implement it, that would be great. Otherwise we'll get to this eventually and get it merged. Thanks for submitting this!

**Comment by sachinraja** [comment]
Are you sure? Looking at the CI errors, it seems like swc failed to install.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

I had to rebase and bump some versions and had no push rights. That said, @sachinraja you are still marked as a contributor on the other PR I opened #5593.

Thank you for your initial work!

**Comment by sachinraja** [comment]
Awesome, glad to see this merged!

**Pull request closed without merging**
