### PR TITLE
Don't use `cursor: pointer` for buttons by default

### LINKED ISSUE #8961: Buttons have cursor: pointer by default, but should not for accessibility reasons
**What version of Tailwind CSS are you using?**

3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 3.0.0 (rollup)

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://stackblitz.com/edit/react-tailwind-qds1vc?file=index.js

**Describe your issue**

While it's common to give `<button>`s `cursor: pointer;`, this is an anti-pattern. The [CSS spec](https://drafts.csswg.org/css-ui-3/#valdef-cursor-pointer) establishes that `cursor: pointer` indicates an element is a link.

[This article](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) has some additional justification for this. I understand many users will want to override this behavior back to the common misuse of `cursor: pointer;`, but Tailwind should be correct by default.

### PR DESCRIPTION
**Pull request by adamwathan**
This is a pretty common expectation but as outlined in in #8961 isn't really right. We considered this a long time ago but it felt too against the grain at the time. These days though very UI-forward applications like [Linear](https://linear.app/) are using the default cursor for buttons and I think this trend will continue as more people become aware that `cursor: pointer` is meant for links.

Let's update our defaults here to help nudge people in this direction and make it more common. If people want to change this in their own apps, it's just a line or two of CSS to add to their projects.

Closed #8961.

### CODE REVIEW

**Comment by aleph1ow** [comment]
@thecrypticace why the commit of this pr has been reverted?
Upgrading to 3.1.7 right now and I'm not getting what announced in the changelog

**Comment by thecrypticace** [comment]
Ah because I we wanted to remove it to push out 3.1.7 and when I reverted the commit I forgot to update the Changelog to put it in the "unreleased" section. Sorry about that.

**Comment by aleph1ow** [comment]
Ok thanks for clarifying 🙏

**Comment by DaniGuardiola** [comment]
Any estimation of when this will be released?

**Comment by danny-does-stuff** [comment]
I would love to see this. As a Tailwind user, I expect Tailwind to use the absolute best practices by default, so leaving `cursor: pointer` on button makes it seem like this is correct when it is not 😱. Thanks for the great package!

**Comment by dBianchii** [comment]
L take

**Comment by erikdemarco** [comment]
just see top 1k website. How many website from that top 1k have button with cursor?
or see top 100 largest internet companies (they have budget to hire best of the best UI/UX experts).

Even 5yo child with low IQ knows how to make developer life easier if most of them using button with pointer cursor.

Even worse. tailwindcss.com itself uses pointer for button

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
Terrible take, revert this

**Comment by therealPaulPlay** [comment]
A lot of people dislike this but I think it's a good change.

HTML buttons never had cursor pointer.

Buttons in native apps never had cursor pointer.

People got used to the fact that legacy websites are mostly using links for buttons, hence cursor pointer is displayed, but for modern SPA it seems natural to not display cursor pointer for buttons that aren't links.

**Comment by matinzd** [comment]
> A lot of people dislike this but I think it's a good change.
> 
> HTML buttons never had cursor pointer.
> 
> Buttons in native apps never had cursor pointer.
> 
> People got used to the fact that legacy websites are mostly using links for buttons, hence cursor pointer is displayed, but for modern SPA it seems natural to not display cursor pointer for buttons that aren't links.

The web has fundamentally different interaction patterns than native apps, so comparing them directly misses the point.

On the web, most of the page consists of content that isn't interactive. Text is selectable, images are often draggable, and empty areas do nothing. The pointer cursor has been a consistent visual signal for decades that says, "this element is clickable." It's part of the web's interaction language.

Users don't expect every clickable element to be a link. They expect clickable elements, whether they're links, buttons, cards, or custom controls, to provide clear affordances. Removing the pointer from buttons weakens that signal and makes interactive elements less discoverable, especially when modern UIs often style buttons to look minimal.

The fact that native apps don't use a pointer cursor isn't a compelling argument because desktop apps and websites have different conventions and user expectations. Good UX follows the platform's established patterns rather than trying to make one platform behave like another.

Saying "HTML buttons never had `cursor: pointer`" is just an implementation detail, not evidence that it's the better user experience. If a small visual cue helps users recognize something is interactive with essentially no downside, there's little reason to remove it.

**Pull request merged**
