### PR TITLE
Add CSS `color-scheme` utilities

### PR DESCRIPTION
**Pull request by lukewarlow**
This PR adds utilities for the [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) CSS property.

(Ignore the browser support for the only word it doesn't break functionality in any browser and definitely works in Chrome)

### CODE REVIEW

**Comment by jonnitto** [comment]
Funny, I've the same code in my projects

**Comment by elizabethmitchell00** [comment]
Thanks for the information.

**Comment by RobinMalfait** [comment]
Hey!

You might have noticed that I forced pushed to this branch. The reason is because the PR now uses `next` as the base branch which is our working branch for Tailwind CSS v4. In other words, the feature you implemented here is now written in the new codebase.

The code is ported as-is, so no API changes of your feature happened while moving it to the new codebase.

I also made sure to add you as a co-author because you still deserve all the credit 💪

**Comment by lukewarlow** [comment]
My thinking on this is that more verbosity is better, makes them easily discoverable. dark-only might make someone think this hides this element in dark mode.

For an existing example there's the file: pseudo instead of file-selector-button which admittedly is a bit verbose but people didn't realise tailwind had this variant I think in part because it wasn't a match to the pseudo name. (file might also end up being a future compat issue if other file element pseudos are ever added but that's a separate discussion).

All that being said I trust in the framework authors to weigh up tradeoffs and come to a decision that's right for them :)

**Comment by brandonmcconnell** [comment]
@lukewarlow Absolutely! I'm with it 🙂

**Comment by adamwathan** [comment]
Opened a fresh PR for this one because the merge conflicts were a nightmare for me to try and resolve 😬

https://github.com/tailwindlabs/tailwindcss/pull/14567

Added you as a co-author though @lukewarlow so will still be credited. Thanks!

**Pull request closed without merging**
