### PR TITLE
add boxSizing classes

### PR DESCRIPTION
**Pull request by alberto-bottarini**
This PR adds 2 new classes in order to have control about box-sixing CSS property (https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing)

I often use this property but I can't found it in Tailwind CSS.

Rules are super simple

    .box-sizing-border {
      box-sizing: border;
    }

    .box-sizing-content {
      box-sizing: content;
    }

Maybe these could be renamed in `sizing-border` and `sizing-content`.

### CODE REVIEW

**Comment by hacknug** [comment]
I always have these on my projects and I cal them `.box-content` and `.box-border`, respectively. Useful when other libraries mess with our preflight defaults 👍

**Comment by alberto-bottarini** [comment]
@adamwathan what syntax do you prefer?

.box-sixing-border
.box-border
.sizing-border

?

**Comment by alberto-bottarini** [comment]
@adamwathan should I resolve conflicts?

**Comment by Erik-Roth** [comment]
If it's not too late to add to this... 
I use the above all the time, especially on custom Wordpress. But I have a couple I use a lot as well if it is no too late to get them in as I have been trying to figure out how to add them to the tailwind.config with no luck.

box-sizing: inherit;
box-sizing: border-box;

As far as a naming convention if you add all the different ones in maybe call the prefix boxy?

so like...
boxy-inherit
boxy-border
boxy-border-box
boxy-content
boxy-(whatever else comes up)

Just a thought :)

**Comment by alberto-bottarini** [comment]
Thanks @Erik-Roth for your idea. 
I don't like so much the `boxy` idea because it's not a proper css keyword.

@adamwathan conflicts are solved.

**Review by ghost — APPROVED** [review]

**Comment by Erik-Roth** [comment]
@alberto-bottarini  LOL 'boxy' could be anything that makes it fit and work - it was the only placeholder I could think of at the moment

**Comment by alberto-bottarini** [comment]
@Erik-Roth `inherit` and `initial` values are not included in any Tailwind CSS rule, so i won't added in this plugin.

I hope this PR will be approved soon. I don't see any problems...

**Comment by adamwathan** [comment]
Merged this manually and renamed to `box-border` and `box-content`, thanks! Not sure why the UI won't show this as merged, probably messed something up locally but your commits are there 👍

**Pull request closed without merging**
