### PR TITLE
Use HSL instead of HEX for colors declaration

### PR DESCRIPTION
**Pull request by RomainLanz**
Hey all 👋 

After a small survey in the Discord most people seems interested to use HSL instead of HEX for the default color palette.

There's [many benefits from using HSL instead of HEX](https://www.sarasoueidan.com/blog/hex-rgb-to-hsl/) and even a whole section in the book Refactoring UI (_Ditch hex for HSL_).

### CODE REVIEW

**Comment by CvX** [comment]
I use HSL in my config as well, but what are the benefits of changing the color syntax of the color palette in the default config?

**Comment by RomainLanz** [comment]
Hey @CvX! 👋 

Thanks for your output.
The main benefit I see is that it would be easier to extract to your own config.

I also hope it can help to spread the use of HSL instead of HEX/RGB if framework like Tailwind use it in their default configuration.

**Comment by rellect** [comment]
Seems like a matter of preference... also won't it make the compiled css a bit larger? 7 chars of hex vs 16 chars of hsl (spaces excluded).

**Comment by daanhaitsma** [comment]
I just put together a quick Vue project to compare the old hex and new hsl colors and found the following:

`gray-600` is now the same as `gray-500`, it should be `hsl(216, 15%, 52%)`.

Otherwise all colours remained unchanged. Well done!

**Comment by hacknug** [comment]
There's differences with more colors than just `indigo-900` althought they're not huge. Are we certain there's no way we can get a _perfect_ match?

@RomainLanz how did you convert them? Adam suggested using Chrome's dev tools because according to him that would probably be the most accurate conversion. If this is what you used, maybe we can explore other options?

**Comment by adamwathan** [comment]
It's hard to get a perfect match because HEX can represent a lot more colors than HSL (255^3 = 16,581,375 vs 360*100*100 = 3,600,000).

I think the main benefit of using HSL in Tailwind is that it helps people see patterns in how the color shades are defined and learn a bit about color if they dive in and look at the definitions for the color palette, but beyond that there's no _real_ benefit in terms of how it improves whatever you're building.

One benefit of HEX is that it seems it's actually faster for the browser to deal with:

https://stackoverflow.com/a/43074519/1146430

Probably not in any meaningful way but faster nonetheless.

I'm okay with either option personally, anyone have a stronger opinion?

**Comment by hacknug** [comment]
Either format is fine for me as long as @sschoger and you are okay with the changes 👍 

@adamwathan probably not a good idea but: wouldn't using decimals on those percentages give you more values than the ones you got from your calculations? Just checked the spec and I don't think `S` and `L` must be integers at all.

https://www.w3.org/TR/css-color-4/#the-hsl-notation
https://www.w3.org/TR/css3-values/#percentage-value

**Comment by adamwathan** [comment]
> wouldn't using decimals on those percentages give you more values than the ones you got from your calculations? Just checked the spec and I don't think S and L must be integers at all.

Ah just tested this and you're right, although I *swear* I tested this last year and Chrome wouldn't accept decimal values and always rounded them to the nearest integer.

**Comment by hacknug** [comment]
So maybe now it makes sense to have decimals in the default palette since most people will never see them? (as long as other browsers support it, of course)

**Comment by CvX** [comment]
Re: decimals support and output CSS file size - we probably could transform these HSL values back to a hex form with a postCSS plugin.

**Comment by stancl** [comment]
Another benefit is easier tweaking of the default color palette. I assume slightly rotating the hue of all shades of any color should work well.

**Comment by tlgreg** [comment]
IMO the real advantage of HSL is only during color authoring, not really storage, for slightly tweaking the default colors it could be good, but for own color palette, I don't really see myself going in and changing HSL values there.

The performance benefit is also because the browsers actually convert colors to (hex)RGB before rendering.

There are also not many color conversion tools out there that actually handles fractions for HSL, partially because on color picker UIs they only use integer numbers. The mentioned chrome devtools conversion also rounds the integer numbers btw.

Actually the few tools I had on hand or searched for online all rounded to integers, so I created a quick mockup where I'm calculating conversion with 20 precision (using `decimal.js`) and rounding it to two-digit precision for css.
Created a pen with a table similar to @daanhaitsma 's.

https://codepen.io/tlgreg/pen/rEOayb

**Comment by stancl** [comment]
Not sure how technically feasible this is but if Tailwind converted the hsl values into hex, we could reap the benefits of both formats (ease of developing a color pallette, performance and consistency across browsers).

**Comment by daanhaitsma** [comment]
Ah, the tests should also be updated to expect the new colours. That's a fun one 🙂

**Comment by RomainLanz** [comment]
I used VSCode tooling to do the conversion @hacknug.

I'll update the wrong color, I wanted to know if you want to have a perfect match with decimals or not?

@stancl That could be good, but doing so will remove the possibility to play with those value via your browser dev tools.

**Comment by stancl** [comment]
Perhaps it could depend on the environment? Similarly to how Laravel Mix automatically minifies files when run for production?

**Comment by narwy** [comment]
Maybe we stick with `Hex` for now and see in the future, I think people getting started with a css framework it's easier to use `Hex` and for those who want to use `HSL` have the options to already swap them out? Maybe even a tool/plugin to convert 😆

**Comment by adamwathan** [comment]
We're working on an improved version of the color palette for an upcoming release so unfortunately this is going to end up out of date, so going to close 😕 Sorry, I know it's a lot of work to do these conversion 😞 

We'll likely be using hsla() in the improved color palette 👍🏻

**Pull request closed without merging**
