### PR TITLE
Rework list utilities

### PR DESCRIPTION
**Pull request by adamwathan**
This PR removes the `list-reset` utility in favor of a new `list-none` utility that only sets the `list-style-type`, and makes it possible to add more list-style-type utilities by customizing your configuration file.

It also adds `list-inside` and `list-outside` utilities for setting `list-style-position`.

This is a potentially annoying breaking change, because previously `list-reset` also set `padding: 0`, and `list-none` doesn't do that.

That means that to upgrade you have two options:

1. Replace any instances of `list-reset` with `list-none p-0`.
2. Redefine `list-reset` in your own CSS:

    ```css
    .list-reset {
      list-style: none;
      padding: 0;
    }
    ```

The motivation for this is mostly about simplicity and consistency in the framework API. `list-reset` is sort of an odd class because it sets two unrelated properties, and nothing else in Tailwind (except `truncate`, which I'm also thinking hard about) does that. It meant we had to be careful to always define `list-reset` before our padding utilities for them to be composable, which isn't a huge deal, but was always a weird rule to have to remember when working on Tailwind itself.

I'm a bit conflicted on removing `list-reset` because I do think it's convenient, and I worry I am over-optimizing for keeping the framework itself simple. If people really, really want to keep it and don't want to have to write `list-none p-0` instead, I could probably be convinced the shoulder the complexity. Another alternative is just removing list styles by default in general, and making them opt-in instead, so you'd never have to write `list-reset` but sometimes you'd have to write `list-disc pl-4` or similar to get a normal looking list.

### CODE REVIEW

**Comment by adamwathan** [comment]
Running a Twitter poll right now to help decide if we just unstyle lists in Preflight:

https://twitter.com/adamwathan/status/1105905209073590272

Becoming more and more convinced we should, because if we already unstyle headings then we've already broken any expectation of typography to look "right" out of the box.

**Comment by adamwathan** [comment]
Decided to reset list styles by default based on the feedback on Twitter and discussions with trusted members of the community. This actually brings Preflight closer to SUIT CSS Base which it was initially derived from anyways.

**Comment by leevigraham** [comment]
I know it's a slippery slope but maybe the list reset could be a configuration option. For a simple docs site I generally want some default styling on lists / headings.  I guess the alternative is to not include tailwind/base.

**Comment by tlgreg** [comment]
Yeah, you can always roll your own normalization/reset on those cases. Or still use tailwind's base and override the ul,ol rules after the base globally or with a component type class, if that's not an issue in the project.

**Comment by adamwathan** [comment]
> I know it's a slippery slope but maybe the list reset could be a configuration option. For a simple docs site I generally want some default styling on lists / headings. I guess the alternative is to not include tailwind/base.

I think a better approach would be for us to provide some sort of optional default typography styles you can pull in with a class, like `.rich-text` or something. Generally you don't want the browser default heading styles because they will be different than the values in your config file, although for lists that isn't really an issue.

I make a class like that for every project already, so I will spend some time after 1.0 is out thinking through a decent way to make that reusable.

**Comment by sleicester** [comment]
> I think a better approach would be for us to provide some sort of optional default typography styles you can pull in with a class, like .rich-text or something.

Exactly what we do for CMS based regions of the page, and I prefer to be explicit in these instances, and work with default styling removed, preventing the need for a lot more `list-reset`. Smooth moves.

**Pull request merged**
