### PR TITLE
[0.5] Add object-fit & object-position utilities

### LINKED ISSUE #317: [Feature Proposal] Object-Fit and Object-Position utilities
I haven't found any discussion about adding object-fit and object-position utilities to Tailwind so I'm opening the issue to hear your thoughts on this. I know it's probably something most people won't use in every website but it'd be something useful to have around.

Support for this feature is not excellent and I always provide a [fallback](https://codepen.io/hack_nug/pen/KvjzZJ) via `@supports not` so I'm not sure if it would make any sense to add this. Maybe if it was disabled by default?

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Added support for the `false` state variant
- Added `object-fit` utilities
- Added `object-position` utilities (inspired by `background-position`, since [they can have the same values)](https://drafts.csswg.org/css-images-3/#the-object-position)

Naming is inspired by the `background` utilitites

Closes #317

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@adamwathan Did you already had the time to look into this one? 🙂
Just a friendly reminder tho 😉

**Comment by MichaelDeBoey** [comment]
@adamwathan I think I just need to rebase and put the updated docs in the right repo 🙂

**Comment by adamwathan** [comment]
@MichaelDeBoey Sorry haven't really dug into this too deep yet; at first glance it looks good I'm just unsure what values we should be providing by default which is the bulk of my hesitation.

I'm going to try and get 0.5 out today without this feature since it's not a breaking change, then we can look at getting it in for 0.5.1 if that works for you?

**Comment by MichaelDeBoey** [comment]
@adamwathan Yeah sure no problem for me 🙂
Just saw you were merging all the 0.5 PR's so wanted to give you a heads up on this one 🙂

**Comment by adamwathan** [comment]
"Miscellaneous" is probably good for now 👍

**Comment by MichaelDeBoey** [comment]
@adamwathan Got some problems by deleting this branch on my fork, so created #500 in favor of this one 🙂

**Pull request closed without merging**
