### PR TITLE
Add pre-commit hook + run Prettier over source

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This will make formatting errors less possible and will now run over all sort of files not only `.js` files

### CODE REVIEW

**Comment by adamwathan** [comment]
I'm a bit conflicted on this because I'll often rewrite code in a different way if I don't like how Prettier formats it (which is often), so I don't really love the idea of Prettier formatting the code silently.

Could we instead just run eslint as a precommit hook to prevent people from committing without manually reviewing any formatting errors?

**Comment by MichaelDeBoey** [comment]
I like the idea of not having to bother the way something is formatted.

If I like it or not, Prettier takes care of it and there can't be any discussion about it too.
Specially when working in teams (or OSS), this really has a proven value for me.

**Comment by azdanov** [comment]
I think prettier is useful for larger projects to keep code style the same. Otherwise, each PR must conform to some arbitrary visual standard.

A good example is [Laravel Style CI](https://styleci.readme.io/docs/presets#section-laravel).
>Don't worry if your code styling isn't perfect! StyleCI will automatically merge any style fixes into the Laravel repository after pull requests are merged. This allows us to focus on the content of the contribution and not the code style.

**Comment by MichaelDeBoey** [comment]
@azdanov That's exactly why I added the pre-commit hook 😉

**Comment by adamwathan** [comment]
Going to say no to this for now for the reasons I stated [above](https://github.com/tailwindcss/tailwindcss/pull/855#issuecomment-484877600) – I just don't like letting Prettier do it's thing silently, I'd rather be able to review the results before the code gets committed. Thanks though.

**Pull request closed without merging**
