### PR TITLE
fix: update lilconfig for ESM and Windows support

### PR DESCRIPTION
**Pull request by shellscape**
This PR updates `lilconfig` from v2.1.0 to v3.1.3. Significant improvements to this package include Windows absolute path support as well as ESM config files support. This supersedes https://github.com/tailwindlabs/tailwindcss/pull/14029 which has fallen behind and has conflicts with the upstream branch. This is a critical update for Next.js apps running in development which have dependencies on packages that use an updated version of `lilconfig`. I understand that v4 will not be using `lilconfig` but it's an important update for users on v3.x in the meantime.

### CODE REVIEW

**Comment by thecrypticace** [comment]
We only use lilconfig in the CLI. How would this affect Next.js apps using PostCSS directly?

**Comment by thecrypticace** [comment]
(gonna get this updated regardless — just wondering)

**Review by thecrypticace — APPROVED** [review]

**Comment by shellscape** [comment]
Triage for this issue https://github.com/shellscape/jsx-email/issues/257 concluded that next.js/webpack was eagerly bundling 2.1.0 as the predominant lilconfig version and was not bundling both 2.1.0 and 3.1.2 (from jsx-email) during development. That resulted in errors when users attempted to use a jsx-email config file in the same app that included tailwind. I was able to reproduce that in fresh next.js apps consistently, and was able to workaround by forcing pnpm/npm to install 3.1.2 only via overrides. Super weird case where webpack is misbehaving in this context. I didn't get a chance to triage what in next.js is causing the bundling issue in dev, but that's next on my list.

Thank you very much for tackling this so quickly.

**Comment by thecrypticace** [comment]
Got it. Seems like a Next.js bug there but yeah we should update. Sorry for letting this sit out so long.

**Comment by thecrypticace** [comment]
Will get a new v3 release out today 👍

**Pull request merged**
