### PR TITLE
add col- and row- span-full utility

### PR DESCRIPTION
**Pull request by swyxio**
add `col-span-full` and `row-span-full` per @flybayer in https://github.com/tailwindlabs/tailwindcss/discussions/2467#discussioncomment-87761

i'm new to this codebase so pardon if i missed something but... it looks like this is the only thing i have to do!

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey @sw-yx thanks! Make sure to run `yarn rebuild-fixtures` to update the test fixtures and then double check the diff to make sure none of the changes are unexpected, but otherwise looks good 👍

**Comment by simonswiss** [comment]
Good stuff @sw-yx, thank you. 

And thanks to @flybayer for the suggestion! 👍

**Comment by sw-yx** [comment]
lol i like how the sun never sets on tailwind labs

**Comment by adamwathan** [comment]
Thanks @sw-yx!

**Pull request merged**
