### PR TITLE
feat: add justify-evenly util

### LINKED ISSUE #1082: [Feature Proposal] justify-content: space-evenly
Hey all,

this is a feature request (and PR) to add a utility for `justify-content: space evenly`, named `justify-evenly`.

MDN describes the functionality as:

> The items are evenly distributed within the alignment container along the main axis. The spacing between each pair of adjacent items, the main-start edge and the first item, and the main-end edge and the last item, are all exactly the same.

Support for that value is present in all major browser except Edge and IE ([source](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Support_in_Flex_layout)).

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Resolves #1082

### CODE REVIEW

**Comment by Nasser-allah** [comment]
I'm trying to extend the justifyContent property to add ` space-evenly` since it's not included yet, but it doesn't work.

I've tried the following syntaxes:

```js
module.exports = {
  theme: {
    extend: {
      justifyContent: {
        'justify-evenly': 'space-evenly',
      }
    }
  },
}
```

```js
module.exports = {
  theme: {
    extend: {
      justifyContent: {
        'evenly': 'space-evenly',
      }
    }
  },
}
```

**Comment by manniL** [comment]
@Nasser-allah  As shown in https://github.com/tailwindcss/tailwindcss/pull/1083/files#diff-9b4af753d607dfdd6b86b9fc1032c5b9R20, a plugin is used and extend won't help there. Thus this PR.

**Comment by adamwathan** [comment]
Originally we left this out because it has no support in IE11 or Edge, but since Edge is moving to Chromium it will eventually be safe to use so whatever. Not my place to tell people they can't use something with incomplete browser support.

**Comment by subhero24** [comment]
This should also be added to the docs, where justify-evenly is still missing

**Pull request merged**
