### PR TITLE
Add class-table partial to make class tables more maintainable

### PR DESCRIPTION
**Pull request by adamwathan**
This PR adds a new Blade partial to the docs that lets you pass in the data for a class table as an array instead of duplicating that table markup everywhere.

I've converted background colors and background position as an example, but it's fine for us to merge this without converting everything at once.

The ultimate goal is to add a Vue component for this that only shows the first x rows by default, with a "Show all" link at the bottom. That way super long class tables won't disguise the fact that there's other documentation below like they do now.

### CODE REVIEW

**Comment by adamwathan** [comment]
Gonna add the Vue component to this PR too what the hell. So I guess we won't merge til that's all good 😄

**Comment by MichaelDeBoey** [comment]
@adamwathan Nice addition maybe, would be to have the header be sticky? 🙂

**Comment by adamwathan** [comment]
@MichaelDeBoey Considered it for about 30 seconds then realized it would be hell because the column widths are dynamic and I can't see a way to make it sticky without splitting it away from the other table, and trying to synchronize the widths between two tables sounds horrible 😄

**Comment by MichaelDeBoey** [comment]
@adamwathan The custom Vue component would help a bit better I think? But indeed maybe not worth the work... 🙂

**Pull request merged**
