### PR TITLE
Prevent @apply from adding !important.

### PR DESCRIPTION
**Pull request by jackmcdade**
This PR addresses #299 and prevents `@apply` from adding `!important` to the output when you have using `{options: {important: true}}`.

### CODE REVIEW

**Comment by psren** [comment]
Oh NOOOOOOOOOO, please not.
I love ```!important```. Specitifity is still higher if i *want* to overwrite (and using ```!important```.

This would be a huge BC-Break for me.
I KNOW WHAT I @apply

**Comment by adamwathan** [comment]
@psren Can you elaborate on use cases where you are using `@apply` to apply `!important` declarations? I can't think of any situation where I'd want to do that; I would always want to be able to override what's in my components with utilities.

**Comment by psren** [comment]
Ah sorry @adamwathan 
I just read the testcase and I have misunderstood hat.

**Comment by jackmcdade** [comment]
@psren Hah! This all about being _able_ to use !important :)

**Comment by adamwathan** [comment]
Merging but have a couple additional things to add related to this before tagging!

**Pull request merged**
