### PR TITLE
Support all color values from CSS Colors Level 4 spec

### LINKED ISSUE #4677: Alpha utilities do not apply to HSL colors using space-separated notation
### What version of Tailwind CSS are you using?

v2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js v11.0.0

### What version of Node.js are you using?

v15.2.1

### What browser are you using?

Firefox

### What operating system are you using?

macOS 11.4 (Big Sur)

### Reproduction repository

https://github.com/htunnicliff/tailwind-hsl-issue

### Describe your issue

Colors that are defined in tailwind.config.js that use [space-separated HSL notation][1] are not handled correctly when used with color modification utilities like `bg-opacity-{n}` or `text-opacity-{n}`.

For example, if I add the same color using the the two notation styles to my config:
- **evergreen-spaces**: `hsl(152 75% 40%)` (uses space-separated HSL notation)
- **evergreen-commas**: `hsl(152, 75%, 40%)` (uses comma-separated HSL notation)

And then I use those colors in conjunction with background and text opacity utilities:
```jsx
export default function Index() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen space-y-8 text-white max-w-md text-center mx-auto">
      <div className="bg-evergreen-spaces bg-opacity-50 p-6 rounded-lg w-full">
        <code>hsl(152 75% 40%)</code> + <code>.bg-opacity-50</code>
      </div>
      <div className="bg-evergreen-commas bg-opacity-50 p-6 rounded-lg w-full">
        <code>hsl(152, 75%, 40%)</code> + <code>.bg-opacity-50</code>
      </div>
      <div className="text-evergreen-spaces text-opacity-50 p-6 rounded-lg w-full border">
        <code>hsl(152 75% 40%)</code> + <code>.text-opacity-50</code>
      </div>
      <div className="text-evergreen-commas text-opacity-50 p-6 rounded-lg w-full border">
        <code>hsl(152, 75%, 40%)</code> + <code>.text-opacity-50</code>
      </div>
    </div>
  );
}
```

This is the result:
Screen Shot 2021-06-17 at 9 47 49 AM

As you can see, the comma-separated HSL values have their opacity changed, while the space-separated HSL values do not change.

Since space-separated HSL values are supported by evergreen browsers, it seems like Tailwind should support them as well.

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl()#space-separated_values

### PR DESCRIPTION
**Pull request by htunnicliff**
@adamwathan in response to your [ask](https://github.com/tailwindlabs/tailwindcss/pull/5003#issuecomment-881978909) that I include support for space-separated RGB values in addition to space-separated HSL values for #5003, I did some research. 

I discovered several newer (well-maintained) color libraries that have **full support for all color types used in the CSS Colors Level 4 spec**.

As a result, I replaced the `color` library with [`culori`](https://culorijs.org/) instead. This supports both RGB and HSL colors with and without space-separated values, as well as [all of these color spaces](https://culorijs.org/color-spaces/).

P.S.: Culori's [API](https://culorijs.org/api/) is quite robust, and as a result could support lots of cool future Tailwind color modification features, if desired 😄

Resolves #4677.

### CODE REVIEW

**Comment by htunnicliff** [comment]
Hi @RobinMalfait and @bradlc 👋  – would you be able to take a look at this PR that improves Tailwind's support for newer CSS color formats? 

I was chatting with @adamwathan about it in #5003 but it looks like he is not available at the present time.

**Comment by htunnicliff** [comment]
Hey Tailwind team; following up here. It's been about two weeks since I submitted this PR. Is there something else I should do in order to receive a review?

**Comment by florianbouvot** [comment]
@htunnicliff it's the holidays 😜

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

I fixed the conflicts and merged it manually. Not sure why GitHub didn't mark this as merged, but your commits are there!

**Comment by danburzo** [comment]
Hi everyone. Happy to see this PR merged! The [latest package version](https://github.com/Evercoder/culori/releases) is `culori@0.20.1` and includes things like parsing the `color()`syntax, which may be useful.

**Pull request closed without merging**
