### PR TITLE
Refactor multiple base utils

### PR DESCRIPTION
**Pull request by 20lives**
I have noticed there is heavy use in chained ```mapKeys(mapValues)``` so I added util that does that in one call

### CODE REVIEW

**Comment by 20lives** [comment]
You probably didn't have time to go over this with all of the v2 rushes,  I have extended the use of the mapObj util, many of the utilities I covered are almost half-length, much less nested, and probably more readable.

**Comment by 20lives** [comment]
I would prefer splitting it into multiple PR's but they all count on the `mapObject` util

**Comment by 20lives** [comment]
Hi, @adamwathan do you find this useful? any point in keeping this up to date?

**Comment by adamwathan** [comment]
Sorry for the delay, I've been doing a bad job at making time for keeping up with GitHub stuff lately but starting this week I'll be spending every Friday on issues/PRs, so I will definitely process this properly for you then 👍🏻

**Comment by adamwathan** [comment]
Hey really sorry I never got to this 😞 The codebase has been refactored a lot since this PR and I don't think there's any clean way to salvage any of this so I'm going to close.

Sorry @20lives I know this was a bunch of work :/ Hope this doesn't deter you from contributing in the future, I really do appreciate it ❤️

**Pull request closed without merging**
