### PR TITLE
Add text-shadow utility

### PR DESCRIPTION
**Pull request by driesvints**
This is a resubmission of https://github.com/tailwindcss/tailwindcss/pull/881. I used @benface's original commit so his works doesn't gets lost. I updated the styles with the current version of his https://github.com/benface/tailwindcss-typography plugin. 

At the moment I'm not sure if the current styling is the wanted one. I tried it out locally and it seems to be ok but not sure if `sm` & `xl` versions are needed or if the current styling needs tweaking. It seems to be that opinions could differ quite a bit on this.

Closes https://github.com/tailwindcss/tailwindcss/issues/307

### CODE REVIEW

**Comment by benface** [comment]
The styles used in the README of my typography plugin are just meant to be examples, they’re not a default value (I’m not sure I even tested them haha). In fact, the plugin doesn’t come with a default text-shadow, exactly because it would be too opinionated.

**Comment by driesvints** [comment]
@benface so would you recommend to just keep your original commit?

**Comment by benface** [comment]
I don’t know, I would listen to what @adamwathan has to say first :)

Thanks for making the PR! The original one got auto-closed when Adam deleted the `next` branch and I didn’t get a chance to make a new one (I forgot, really).

**Comment by adamwathan** [comment]
I'd like to get Steve to pick some good default values for this before merging, I'll ping him about it.

**Comment by hacknug** [comment]
@adamwathan @sschoger will this be a part of the TailwindUI update? If not, I think it would be a good idea to add the plugin to core even if we don't provide any default styles for it yet.

**Comment by adamwathan** [comment]
Going to close this for now because no concrete plans to tackle it and it's been sitting around for a long time. Will re-open and integrate the original changes if possible if/when we do add text shadow support in the future.

**Pull request closed without merging**
