### PR TITLE
Enable more variants by default

### PR DESCRIPTION
**Pull request by adamwathan**
This PR enables the following variants by default:

- Focus variants for background colors
- Focus variants for border colors
- Focus variants for font weight
- Hover variants for box shadows
- Focus variants for text colors
- Focus variants for text style (underline, capitalization, etc.)

It adds significant size to the CDN builds but it makes the default build much more useful out of the box. We have [thorough documentation on managing build size](https://tailwindcss.com/docs/controlling-file-size/) so I think it's silly to cripple the default build just to make the framework appear smaller to people who don't spend the time to learn about how it actually works.

### CODE REVIEW

**Review by reinink — APPROVED** [review]
go

**Comment by MichaelDeBoey** [comment]
@adamwathan Don't forget to change the [variants](https://github.com/tailwindcss/docs/blame/master/source/docs/background-color.blade.md#L51) in the docs either. (Do I make a PR for it?)
Maybe we can get the variants from the config in some way, so this isn't any problem anymore in the  future?

**Comment by adamwathan** [comment]
@MichaelDeBoey Yeah definitely need to do that, would welcome a PR if you're around to do it today, if not I'll get to it myself at some point before the end of the day 👍

**Comment by MichaelDeBoey** [comment]
@adamwathan PR is on it's way 😉

**Comment by MichaelDeBoey** [comment]
@adamwathan You can check tailwindcss/docs#24 for the PR 😉

**Pull request merged**
