### PR TITLE
Add border-width: 1px for horizontal rules

### LINKED ISSUE #979: Bug? Horizontal rules are invisible by default
The `border-width` reset in preflight causes `hr` elements to be invisible by default:

https://github.com/tailwindcss/tailwindcss/blob/ca670f5a764d53185a16545f8b51868af1fd47b0/src/plugins/css/preflight.css#L100-L106

Easy fix is to add the `border` class to `hr` in your markup, but maybe it makes more sense to set a 1px border for `hr` in preflight?

Not sure if I like the idea of allowing specific values from tailwind's design system to leak into preflight, but I also am not a huge fan of every `hr` being invisible unless you add the `border` class or override preflight 🤔

### PR DESCRIPTION
**Pull request by AlexVipond**
Fixes #979

### CODE REVIEW

**Comment by adamwathan** [comment]
Thanks @AlexVipond!

**Comment by alexdilley** [comment]
Was the intention to make `<hr>`s 1px in height? Because a 1px border on all sides makes it 2px tall.

**Comment by brunolemos** [comment]
Should probably be `border-bottom-width: 1px;`.

**Comment by adamwathan** [comment]
Yep agree, will fix this for the next patch release. Sorry that it'll be another breaking-ish patch 😩

**Comment by AlexVipond** [comment]
> Was the intention to make `<hr>`s 1px in height? Because a 1px border on all sides makes it 2px tall.

My intention was just to find something that looked like a good default—I was designing in the browser and not giving much thought to the actual pixel height of the element. Although if you put me on the spot, I probably would've have guessed they were 1px tall 😅 

Personally I don't have a strong preference between a 1px or 2px tall default border. Maybe it's time for another @adamwathan twitter poll?

**Pull request merged**
