### PR TITLE
Improve sorting candidates containing numbers

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR adds a custom `compare` function that compares two strings. However, once a number is reached the numbers are compared as actual numbers instead of their string representation.

Before this change, `p-1 p-2 p-10 p-20` would be sorted as `p-1 p-10 p-2 p-20`. After this change, the order is `p-1 p-2 p-10 p-20`.

This makes the suggestions in the vscode extension more logical.

The implementation compares two strings, and as long as the strings don't contain any numbers, it compares them as strings. This way we don't pay a performance penalty for comparing strings that don't contain numbers.

Testing this change on the `tailwindcss.com` codebase where we have to store `~3200` unique classes the time spend on sorting the classes went from `~2.35ms` to ~~`~3.29ms`~~`~3.10ms`. This means that there is about a ~~`~1ms`~~`~0.75ms` performance penalty for sorting this.

Another thing we could have done is to compare using the `localeCompare` method:

```ts
function compare(a, b) {
  return a.localeCompare(b, undefined, { numeric: true });
}
```

However, this is an order of magnitude slower than the current implementation, and sorting takes around `~30ms` instead.

---

Outstanding questions:

1. ~~We could _only_ do this for the VS Code extension and Prettier plugin because then we wouldn't have to pay the performance penalty of ~~`~1ms`~~`~0.75ms`. This however means that the order in the extension or the Prettier plugin would be different compared to the order in the generated CSS. Should we only do it there or everywhere and pay the ~~`~1ms`~~`~0.75ms` penalty in favor of nicer consistency?~~ The performance is below ~1ms so good to include everywhere 👍

### CODE REVIEW

**Comment by adamwathan** [comment]
Nice — hard to tell just scanning the code but what's the behavior for strings that have numbers in the middle of them (`pt-48-potato`)? Or classes with modifiers (`text-16/loose`)?

**Comment by thecrypticace** [comment]
Something like `text-16/loose` vs `text-16/wide` should get sorted alphabetically because everything up to the `/` is identical. We should definitely add a test proving this though.

**Review by thecrypticace — CHANGES_REQUESTED** [review]
Everything looks good from what I can tell, but we should add some more tests for utilities with numbers and modifiers. (Just in the compare tests seems fine to me)

**Comment by RobinMalfait** [comment]
I'll add some more tests cases 👍

**Review by thecrypticace — APPROVED** [review]

**Pull request merged**
