### PR TITLE
Adds cursor-text class

### PR DESCRIPTION
**Pull request by marina-mosti**

### CODE REVIEW

**Comment by adamwathan** [comment]
Hey! I think this is probably a reasonable one to include by default but could you give an example of where you might use it just to be sure? Thanks!

**Comment by marina-mosti** [comment]
Hey, i've mostly used it for example when a piece of text is contained inside a card element or something, and we try to make it really obvious to the user that if they click there some sort of editing will occur. When the parent card is clicked, we turn the whole interface into an editable text area.

**Comment by marina-mosti** [comment]
https://codepen.io/immarina/pen/Lvqagd :)

**Comment by adamwathan** [comment]
Great thanks, I've added it to the `next` branch so it will be in Tailwind 1.0 when it is released very soon 👍

**Pull request merged**
