### PR TITLE
create defineConfig utility

### PR DESCRIPTION
**Pull request by lemuelflores**
I saw an issue and  discussion opened so I'm not opening another one for this as the CONTRIBUTING.md says

- #6422 
- #1077 

This PR adds a utility function that correctly types your config so it can be referenced in Javascript code properly.

It accepts the config TailwindCSS is expecting but returns the concrete implementation.

Here's the Typescript Playground that shows you can get the desired config: [Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCIXgVwDZgMID22BUAzsgN4CwAUMsqABbTBgBcyA5Ey2J7fQSYoUCOA6chIsfiIl+dZGChwQpAA5xR4rstUatMhfQBG2RAGsJAYgAM948gDujVhBsxPj0ucgdqivScAKy2nB4AHPAwCI5BAIwOHvEwwTAAnHFcAExJXNYQ2RBRYQL0XADMeZzWCCYAJsEQ8VmcACzV1ultcBUmEa2hYTYAbG0A7G0RJq0jnRPBwSOZZUHjnRUVbfGLrRGd8YXpfa3pnbYw8ePZcI4AvmUA5ioAnv6rXKHh+RnRMx+cRLDH4VGBtGAjVq5YE1CBNcYQf6BSqderxRr1JHlLgdGFdBC9OAwQadEYma77WbzEyLEYVVrrPEVSY7FoA-Z4lLZY7jU4HeLxCLZXllB6KABeoAQ72RITx0SJtwBQO+NTB6uCUM6EDaOogItlVTx9TaJvqAwBuNV1jg8VtcCVsqG1vGVyujuxnDmeOC2V9wSx5U4jOtoNBbUh7M6wpjHqDZ05EUF8UDYvoIAgmD02Blnq+HkV8FaKo8aTLWrxcKrmoBRutZtNbVaVpshIqvRJePGzJ7VJ9foHDPmtg6HT20ZG2UnkdlCetbtdBvoaeQpDABAzuaD+Z+hZWspLPzLYIr1v1VabtdRI3qFTRzc6cAicG5EE7LoirpGsQB3utwXGYItjfAEQxsNoINsCof1lDlrW5AdL1nA4EHidIrnuMpRHqLcgh3NUMGyGBsmLToYAgQpClPDwIAJAlWjrDwCWCOAa1lFsfk-N13xsDAIIgvt6wQKcpyHPETHQ1CYM9OCbHSdCTBTPku0uNF6kwxQSFUR53EoAF8OsTwYARdTlTI8j6kaaifggepxgdBiyMxOBJgfeUJOyaCeJ+dJu3iGdPT-XjWP2aSgzA-JhO2WwwqCWT8nSXpthIgE5xscZhLRFLFBXOAAFsTGgXDPnlTxCsDBIyIwaClyDaFrRgeoIBGZ9HPlBBb1NNyGpMExiKQvMyOCdIIFsCquCC-J6l89YAvCzoTDaIDbH3GTOnSbJcRA5CuwiCpQmJUUyheCBsGIJxirlBqMCQC0DyqjIEHpAF6pomBbFaq95SakdaqCDi1UQVC2MGys4BMKo7sCzoCWfEcxOtW1J1sP6uHimoImCU1bG2z00vyV1QXibLlzKbBgDy3SAkGhrxnI-VSMrBAYjqayammjJ0lMw0FsIsZutbCpmv27yMbaBBULmoJJpqEYWKqbnPQimpTQyi5xyZCFsmJ5TQzlip4gG5AV2eCiQEugz3sak8zONZmkFRzhXvyXrjPqUoebxCIRgwRABfyHomspfTo2yBBFlxoMZesfykrjNYDmCfY7w1+cRn1o2gnxmpDaA7JFeNsoIEplRsBwvSnSZ62QaDQ92ZSOA4TZm06bvD3PUY-Iff1cl-ZqLZb3k0WY7G9Ik0EmxbGG9PVvmvFfsxx30bsOWwSlrhs5X3UTiOxRIDgHMK5pjwLnqItbetCWYD6tlZWdmp5IhHU2v-Ci4BNPvrHzk0+uHw3+jgOvL05xppTChnPa0Fxxjp0jnFfkTRhq6xsPEYCPQNKCBeKoC2VcMCHXuniZm0RYE5EfGkUEsUUR4hGAiKIs9-qh1vBRYetgyQ3kzhNc4EQFIkwgZPfUbQzip2QRHQCSD8j+V1HSdBq4LBvCPtueUFx0heAvrxC4RFiFOwWo3EYjUX7pUsuQz+FRphn3AXhc4EBWIQDoRw+e2QIji0dsrOwFRli2iEfkFGw1MZiJqDFHoPtpFmEwFTEOZ5PC6LwZ6Ou1hMRWPIs3PqmJElfWtMccOejLSklsKxc+lcmT9CIkA6Ofo6SIgRsgk0tlzFowODqXJ0T4z1PbJ9HKZRQD1GAI8Ag2CzyERUfgs8OM6ZNKCPfWo4x6gaP0fkVii0YifyTBEZmtS5RULcbo2+0M8TggjE3UC8xNgrPjnUpk3ZcnPR2qGYmxRtmF0UAAN2AEQCA7B5EWIamQwZMTtRNWUZoiZll6i6M0Z3GoCA2g0iyexR84xpj5NBtaaYwRmYlM6BldstlKld2mREaaniagBm1iYIBm9xbonSDXFc6hhDqGwGEyuDUiRpDGVwWJMAhZRDZVoysXNWWzPZtMcEmiAa1A+uCCh6zEaYzSI7aOxxNhWJxTUBE2Qw6aOXmSbWT4-HWCTvEBAn5pEwEwAgRgpBgBwD6R4M+4IeUcsbty5uqR3apM9g1XJfUpViuKOMZRtjpU2FAT7Hl0cEC2CnLeFVNptYEh5cvb2aEoh6vWHaURu96DqFAFYD5JUGpnyImsjlDtOUupMMzYogrDKJXxew9oZEJjZFJcPWiUwh6-lRCYYU4xnG80FMEAucC8RcyuF1VKnQ9qCjaFc0migoAEFIIy4+PxPBckZg1cikiXW0UMdWxqcAeg8rFdfV0viQ7yhnakTR0dmjoimDGwqxMvJRhHZcTygbN4RCTJsWqK4AD0AAqQDyAAACTV1CiAJJAeoyAACC5ACAwGQAAFTgMAbAThOnIDwAAZVw8gR52QAB02QAA0yAAAG5NHiMDAAAIWwKEyjyBGBwHIIVMQyBtD5VskoAgVHSCyMo8R5AABVdQ9Q4CQGQC8AgwhkAIA3DAbpwhpMvJAMgFTDL+Orgw2IJAShXDkCcFoEAoBHiicA-+5ANG6OMdCRwdAWBcCEGIGQAA2pwITLxOAAF0yhAZA+BiAkHaLSb4wh5ASHUPocw9hvDBHHkVGI7YCjlHTNQDygAcVeCxtjHGzbcbELx2D65BPrgzCJ8TkmIuyfk1ARTynVMqDABprT+ndOWoZSAQzYBjPODMxZqzNnMs5deE532OBZDudIF5tcG43wBcUEFsDEGoMRdg1FmLaGMNYZALBxLhGUtpao8oUJuW4AvHy+x5AnHNM8cpmVgTlGMxZlLtViTUmZNyYU0pkAKnHhqbaxuDrOnyvdYMygfrwATNDZAJZ5A1mlBQAuxNtAU3XNyE85wN72Z-OBeA2t0LG2YPwcQ8h3b8WDs4fw8d1L6WlNEEu9d1jt37vFZAKV3TlHnhXc+7Vn7DWmsA5a+p0H2nocCch716HA3MvmYRyNprzP0fObgNNtzJA5ucD5755b9BVshbC9ByLFPYt7YS3T5LDOqMhIgCzm7hWuOPb4+VyjPgIsC++ygX7jX-uA+B+1yXXX9Oy6M7DwbUBFeI+R-blnk2XMze1-N3wS3aBiloKASAsBEAoAAApMceKAMTbXsDkGpk12bieNdY9m2UfrxcIAAApND9Y4GuKAFmKNNSTwANQPqEgA-BwTAIALAgAIE4EAABKDgqgXhlBMKIOAFh1AEGz6QAAPAASWQAAXmQAAJVoiQeoW-O-d+QGPifU+QAAD4KMAHkD-IB3-f5vWhHgcB33P5AT+sJHgTBP8oBv9VxlALM-8QCwD88tA2sD4t8KBotNAEBWAXgB8u9wYGUO8ICEcABuZAxANAgfJjXSEATAAqaAY2e-GfA-e-cArvBHMoC1bAaAnAxgx4KAr-DgWAqAeA7ARAwg1AsAdArQK1MwXSS-fAoQ4gwfMgigwqRrO4GgughgizDPWgWgEQ9QFAE-UgIgR5LAiAFDAgLfFDegw-FDZAAAH2QGb2byzAw1IB4KLxLzL1IFoP33oJQxn00JoGz2gHgEMxPykEtUeQgAAGkIBRDSDYDgAoAt8IjkAIAAAPSAA7cgCwaImLBfV-KQx4CjPvPI3Ax4egyvDzLIuRfIvzDgIo2wkI4QMIyI6Ikg0JOIhIiIwo+-DQmgLPcAQIvPVDZgSmQgUXR4eRJTavY-CAfQ7AQwiQkwrfBosgYAcIqImIto9DKAbomgTPfw-o3PYIiAAAR0wHiNslGMBwmI3HSPeQXx6L6JzyCJQCf3UBBy52wEuO6XkUb0ph4LgKtQEJQ2GIgC+PGIADJKBki0ixBy5eD+CzCQSwT6DlCHiaBtCUAwTX8T9Tjzj6gsTIT4TASt9Xj3iD5kS-DaBTVet3jitZjwiwSzDoT0j6hyBkTm8A9ukOAfDuT5FRAwBhBNNOTHg0T-s1xkA8oXgwSOAsTD9K9-tbiOAPM-MyMG8QTipJjtdipTBSCOAAAie3PU1U5EegBdJdbU8oPU0IPU-Us0iAAAWmtI+DnWxBXDFD2LFLABFyuMP1EHpNBOa0eGb0lLBN8N6JoGFOI1+IgGI01LIGI3t1oEjOjNjOx1IGIztK8y+GWypLHwQFpN71AADLGKZNSJZLZMDI-2FO5L-ysMr35MFO9O6VFI3HFOFOyFfz9IMOLMB2b0LIzDBOb3lJuJkCVJVLVKbw1LTItPt31MNONOxFNMXWXUXPoCtNsBtOQD1LtMdI3OdIeVdN3juBnzDKTMDJIxTLjPTPtyAA)

Usage:

```javascript

module.exports = defineConfig({
  content: [],
  theme: {},
  // ...
})
```

Screenshot:
image

### CODE REVIEW

**Comment by thecrypticace** [comment]
Hey, appreciate the PR.

We floated the idea of a `defineConfig` utility for v3.2 but we decided to go a different route. For JS users they have the ability to use a JSDoc type annotation to get the same effect. As for TypeScript users, you can type the variable as `Config` directly (as you've done in one of your examples).

Obviously there's a slight difference in directly typing something as `Config` versus using a generic + extends. However, with the release of TypeScript v4.9 next week this will no longer be a problem with the new `satisfies` operator. So you'll be able to do something like this:

```ts
import { Config } from 'tailwindcss'
let config = {
  theme: {
    extend: {
      colors: {
        primary: 'red',
      },
    },
  },
} satisfies Config
```


Now, with regards to the change to `resolveConfig`, unfortunately directly returning the type using generics is not 100% correct. This is because `resolveConfig` merges configs from `presets` and from `extends` into a "flattened" config object. So the type you get back, while it is a valid config, is not exactly the same as the type you passed in.

For example, after resolving the following config:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [
    {
      theme: {
        extend: {
          colors: {
            primary: 'red',
          },
        }
      }
    }
  ],

  theme: {
    colors: {
      secondary: 'green',
    },
    extends: {
      colors: {
        tertiary: 'blue',
      },
    }
  },
}
```

You get an object that:
1. Has all defaults filled in (e.g. what core plugins are enabled, the default dark mode strategy, etc…)
2. And also has the below structure with regards to `theme.colors`:

```js
{
  theme: {
    colors: {
      primary: 'red',
      secondary: 'green',
      tertiary: 'blue',
    }
  }
}
```

The resulting object won't have presets or extends in it as it is a flattened config.

We definitely recognize the usefulness of being able to type a config directly and get more guaranteed, type safe information out of `resolveConfig` and we may look into adjusting the types to encode this behavior in the future. However, it would be quite a time sink and require continual maintenance to keep the types in line with tbe runtime behavior of `resolveConfig`. As such I'm going to close this PR but I really appreciate you taking the time to put it together and the effort you put into it either way. Thanks! 🎉

**Comment by xxRockOnxx** [comment]
Definitely forgot about the `resolveConfig` merging `extend` to the original object.
If anything, I just learned that Typescript 4.9 is coming and part of it is solving this exact issue.
Thank you for the time checking this PR. Appreciate it! :tada:

**Comment by nareshbhatia** [comment]
Trying to get this to work with TypeScript 4.9.4.

- I renamed `tailwind.config.js` to `tailwind.config.ts`
- Changed the content as follows:

```typescript
import type { Config } from 'tailwindcss';
import colors from 'tailwindcss/colors';

const config = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    colors: {
      primary: colors.blue,
    },
    extend: {},
  },
  plugins: [],
} satisfies Config;
```

I am getting the following error with the `satisfies` syntax:

> Newline or semicolon expected

If I remove the `satisfies Config` that error goes away, but I get the following error when I try to run the Next.js application:

```
error - ./src/app/global.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[13].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[13].use[3]!./src/app/global.css
TypeError: Cannot read properties of undefined (reading 'config')
TypeError: Cannot read properties of undefined (reading '')
    at resolveModuleMetaData (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:204:82)
```

I suspect that it is not able to find `colors.blue`.

Has anyone got this working?

**Comment by Walidoux** [comment]
up !

**Pull request closed without merging**
