### PR TITLE
Make dependencies of config watchable

### PR DESCRIPTION
**Pull request by serg-plusplus**
#488

### CODE REVIEW

**Comment by qntndev** [comment]
Looks like you solve [this problem](https://www.youtube.com/watch?v=sCL6Ve-UFcM) !

Please merge @adamwathan 🙏

**Comment by serh11p** [comment]
@adamwathan , how can I help with continuing this staff?

**Comment by adamwathan** [comment]
Sorry just haven't had a chance to play with this yet! One thing I noticed looking briefly but unsure if is true, does this recursively watch dependencies?

Say I have a file like this:

```js
const plugins = require('./plugins')

module.exports = {
  // ...
  plugins: plugins
}
```

And inside plugins I have this:

```js
// plugins.js
module.exports = [
  require('./buttons'),
  require('./form-controls'),
  require('./animations'),
]
```

Would the `buttons.js`, `form-controls.js`, and `animations.js` files be watched? I think that would probably be ideal but even if not this is still better than what we have now 👍

**Comment by serh11p** [comment]
Yes, this recursively watches dependencies

**Comment by adamwathan** [comment]
Awesome, tested it out and works great 👍 Thank you!

**Comment by garand** [comment]
@serh11p @adamwathan This doesn't appear to be working if the required file is from an NPM package. Any ideas?

**Comment by adamwathan** [comment]
That’s by design, watching the entire tree of dependencies through to node_modules makes things really, really, slow, and it’s sort of out of the ordinary to be editing files directly in node_modules. What’s your use case?

**Comment by garand** [comment]
@adamwathan Yeah, you're right... currently I'm developing a design system and separate app that consumes that design system in tandem so I'm importing the Tailwind config from the design system package (`npm link`'d). Of course after I finalize everything the config won't be changing, so this is working as intended, and for now I've changed my require statement to go up a directory to find the file instead of through the package. 👍

**Pull request merged**
