### PR TITLE
Add configurable naming support for classes

### PR DESCRIPTION
**Pull request by dumconstantin**
By using a dictionary for css names, different flavours of terse/verbose classes can be generated.

### CODE REVIEW

**Comment by dumconstantin** [comment]
Oh, forgot to sync fork beforehand... doing it now.

**Comment by dumconstantin** [comment]
Ok, it's sync'd with the latest master.

**Comment by adamwathan** [comment]
You are a mad man 🤣  This is cool but I don't think we want to add this level of customizability to the framework right now; it removes any remaining conventions we have and makes it a lot harder to create shared resources around the framework.

We might reconsider something like this down the road but have to say no for now, thanks.

**Comment by dumconstantin** [comment]
:sweat_smile: No probs! I needed it to scratch my own itch so I'll need to maintain it going forward :)

**Pull request closed without merging**
