### PR TITLE
Adjust shadow, radius, and blur scales to ensure all utilities have a value suffix

### PR DESCRIPTION
**Pull request by adamwathan**
This PR reworks the default `--shadow-*` and `--inset-shadow-*` scales to remove the bare `shadow` and `inset-shadow` utilities, and ensure every shadow has an explicit size as part of the utility name.

Here's a complete list of changes:

| v3                | v4 Alpha          | Proposed           |
| ----------------- | ----------------- | ------------------ |
| _N/A_             | `shadow-xs`       | `shadow-2xs`       |
| `shadow-sm`       | `shadow-sm`       | `shadow-xs`        |
| `shadow`          | `shadow`          | `shadow-sm`        |
| `shadow-md`       | `shadow-md`       | `shadow-md`        |
| `shadow-lg`       | `shadow-lg`       | `shadow-lg`        |
| `shadow-xl`       | `shadow-xl`       | `shadow-xl`        |
| _N/A_ | `inset-shadow-xs` | `inset-shadow-2xs` |
| _N/A_ | `inset-shadow-sm` | `inset-shadow-xs`  |
| `shadow-inner`    | `inset-shadow`    | `inset-shadow-sm`     |

The motivation for this change is just to make the scale more predictable — it's never been intuitive to me that `shadow` sits in between `shadow-sm` and `shadow-md`.

This PR doesn't remove the ability to create classes like `shadow` and `inset-shadow` by adding bare `--shadow` and `--inset-shadow` theme variables, but does remove them from the default theme.

## Impact

We'll include a codemod for this in our upgrade tool to automate this change for people upgrading from v3 to v4, but this is still sort of an annoying breaking change admittedly and will make lots of educational resources, example components, and LLM tools out of date for v4 😕 At the same time I don't want to feel like we can never correct regrettable legacy decisions just to preserve backward compatibility.

We made a similar change like this when we went from the v0.x color palette to the v1.x color palette changing names like `bg-red` to `bg-red-500` and that proved to definitely be the right decision long term, so want to rip the band-aid off here too if we can.

Planning to make the same change for `rounded`, `drop-shadow`, and `blur` as well — maybe in separate PRs but maybe just all in this one as well since I don't think we want to do one and not all.

_Update_: I've also made the same changes to the `--radius-*`, `--drop-shadow-*`, and `--blur-*` scales now, effectively removed the `rounded`, `drop-shadow`, and `blur` classes by default, and changing the meaning `rounded-sm`, `drop-shadow-sm`, and `blur-sm`.

We'll put together a codemod to handle this stuff in a separate PR.

### CODE REVIEW

**Comment by saadeghi** [comment]
I like the new range 👍  

>Planning to make the same change for `rounded`, `drop-shadow`, and `blur` as well 

I think a challenge of using the default theme of Tailwind is, sometimes class names are not predictable (to guess). For example, It's not easy to guess if each token with `xs` or `sm` or… (also some of them have a default)

I think it would be better if they all start at the same name (`2xs` or `3xs` or...)

Here are the other sizings from Tailwind 4 alpha, and since they all start from the same name, it's sometimes hard guess, I think it's a common experience to try typing the class name it in editor and if there's an intellisense and I don't see a suggestion, then I know "oh, this one starts at `sm` not `xs`"

token |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- 
--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- 
breakpoint | - | - | - | - | sm | md | lg | xl | 2xl | - | -
blur | [default] | - | - | - | sm | md | lg | xl | 2xl | 3xl | -
radius | [default] | - | - | - | sm | md | lg | xl | 2xl | 3xl | 4xl
dropshadow | [default] | - | - | - | sm | md | lg | xl | 2xl | - | -
width | - | 3xs | 2xs | xs | sm | md | lg | xl | 2xl | 3xl | 4xl | 5xl | 6xl | 7xl
font-size | - | - | xs | sm | md | lg | xl | 2xl | 3xl | 4xl | 5xl | 6xl | 7xl | 8xl | 9xl

**Comment by steveoh** [comment]
My first thought would be to follow the font size classes and use a `-base` suffix

**Comment by kandros** [comment]
I’m slightly against this proposal, the best feature of tailwind is that is basically a standard library at this point, predictable results unless theres project-specific overrides. The idea that things change meaning across versions creates both a mental overhead (less trust of the result) and technical challenges for things with different versions, eg design systems + app code, federated modules ecc.

considering this is more of “I wish it was different” than a solution to a problem makes me think is not worth it

**Comment by xewl** [comment]
I'm all for the band-aid ripping. A major version shouldn't be held back by choices made in a by-then legacy version. Break all the things 🔥

**Comment by michaelsnook** [comment]
This sounds good to me -- I've been using TW for years and I never understood that `shadow` wasn't the same as `shadow-md`. 

So now, will anything happen if I use the class `shadow`? Will there be a default size / can I configure it? (or will that class name be left open for folks to write their own default shadow rules?)

**Comment by jan-dh** [comment]
The new scale makes sense, would make shadow and alias to shadow-md for predictably though.

**Review by philipp-spiess — APPROVED** [review]
LGTM! I wonder if something can be simplified in the utilities code now that we no longer need to handle an `shadow` (without an argument)? 

In other words, do we still need this branch now or should this just return `null`? 

https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/src/utilities.ts#L4279-L4291

**Comment by philipp-spiess** [comment]
@adamwathan Hmm yeah makes sense... does this mean it should be in the compat layer? (depends on if we want people to use this in a fresh v4 project I guess?)

**Comment by adamwathan** [comment]
> @adamwathan makes sense... does this mean it should be in the compat layer though? (depends on if we want people to use this in a fresh v4 project I guess?)

@philipp-spiess Yeah maybe? Just a question of do we consider the whole idea of being able to have a `shadow` utility to be legacy, or just shipping one by default to be legacy.

I'm not sure how we'd make it work in the compat layer either without unregistering the default `shadow` handler and registering a replacement 🤔

**Comment by philipp-spiess** [comment]
> Just a question of do we consider the whole idea of being able to have a shadow utility to be legacy, or just shipping one by default to be legacy.

Exactly, that's what I was thinking. 

> I'm not sure how we'd make it work in the compat layer either without unregistering the default shadow handler and registering a replacement 🤔

We do have a precedence for this where we just wrap the "core" utility and handle an additional cases: https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/src/compat/theme-variants.ts#L9-L27

**Pull request merged**
