### PR TITLE
Vite: Use Vite resolvers for CSS and JS files

### LINKED ISSUE #15159: [v4] Resolve `@import` or `@source` from `vite.resolve.alias`
**What version of Tailwind CSS are you using?**

tailwindcss: v4.0.0-beta.2
@tailwindcss/vite: v4.0.0-beta.2
@tailwindcss/postcss:  v4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

vite: v5.4.11

**What browser are you using?**

Chrome, Safari, etc

**What operating system are you using?**

 macOS

**Reproduction URL**

https://github.com/TiBianMod/vite-tailwindcss

### Reproduction contains 3 Branches
- `main`: `without tailwindcss` WORKING
- `@tailwindcss/postcss`: WORKING
- `@tailwindcss/vite`: NOT WORKING - Throws

**Describe your issue**

- `@tailwindcss/vite` Can't resolve `@import` or `@source` from [vite.resolve.alias](https://vite.dev/config/shared-options.html#resolve-alias)

- `@tailwindcss/postcss` Can't resolve `@source` from [vite.resolve.alias](https://vite.dev/config/shared-options.html#resolve-alias)

```sh
  VITE v5.4.11  ready in 403 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

7:51:44 PM [vite] Internal server error: Can't resolve '#resolveThisCss' in '/Users/user/Code/vite-tailwindcss/src'
  Plugin: @tailwindcss/vite:generate:serve
```

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #15159

This PR extends the `@tailwindcss/node` packages to be able to overwrite the CSS and JS resolvers. This is necessary as some bundlers, in particular Vite, have a custom module resolution system that can be individually configured. E.g. in Vite it is possible to add custom [resolver configs](https://vite.dev/config/shared-options.html#resolve-conditions) that is expected to be taken into account.

With the new `customCssResolver` and `customJsResolver` option, we're able to use the Vite resolvers which take these configs into account.

## Test Plan

Tested in the playground by configuring  [resolver conditions](https://vite.dev/config/shared-options.html#resolve-conditions) (with Vite 5.4 and Vite 6 beta). An integration test was added for both the JS and CSS resolvers to ensure it keeps working as expected.

### CODE REVIEW

**Comment by philipp-spiess** [comment]
@TiBianMod What's your use case for using these aliases for `@source`? I'd say `@source` is a tailwind-only feature so it doesn't really make sense for me to respect bundler specific rewrites, especially especially as it used to resolve to a directory or a glob and not a single file.

**Comment by TiBianMod** [comment]
@philipp-spiess 
OK I see. Ignore my request about the `@source` for the moment, hehe 😄

**Comment by sdalonzo** [comment]
This seems related to a problem I'm having with the v4 beta.2 in a Rush/pnpm monorepo. The issue I'm having manifests as a recursion issue:

```
error during build:
[vite:css] [postcss] Exceeded maximum recursion depth while resolving `tailwindcss/utilities` in `/Users/sdalonzo/github/monorepo/common/temp/node_modules/.pnpm/tailwindcss@4.0.0-beta.2/node_modules/tailwindcss`)
file: /Users/sdalonzo/github/monorepo/design-system/dsnext-tailwind-radix-proto/src/tailwind.css:undefined:NaN
```

This happens with the Vite plugin and the postcss plugin. I'd be happy to test a build and file a separate issue if it ends up not being related.

Thank you for your hard work on this, I'm excited about getting started with v4

**Comment by sdalonzo** [comment]
@philipp-spiess I'm working on a minimal repro since I need to to open the issue - it'll just take a little while because i have to recreate the monorepo conditions first.

In the meantime, I'm not sure what you meant by adding the .css extension. My css file has `@import 'tailwindcss';` as generated by the upgrade tool, the reference to /utilities seems internal to tailwind.

**Comment by philipp-spiess** [comment]
@sdalonzo Oh interesting! We'll need to figure out where that import is coming from, because the internal `tailwindcss` import just maps to a relative `.css` file: https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/index.css#L5

**Comment by sdalonzo** [comment]
@philipp-spiess even more frustratingly, my repro passed the build and just has some issues in storybook that are probably solvable. I'm working on adding more until I can reproduce.

**Comment by TiBianMod** [comment]
excited for the next release 🎉

**Review by adamwathan — APPROVED** [review]

**Comment by indykoning** [comment]
> @TiBianMod What's your use case for using these aliases for `@source`? I'd say `@source` is a tailwind-only feature so it doesn't really make sense for me to respect bundler specific rewrites, especially especially as it used to resolve to a directory or a glob and not a single file.

@philipp-spiess just to clarify, aliasses in `@source` are **not** supported currently correct?
I have a usecase where the alias is a folder that can change depending on development context.

If it's not currently implemented i'll go ahead and open a feature request for it. Otherwise it'd be quite unnecessary to open a feature request 😃

**Pull request merged**
