### PR TITLE
Improve normalisation of `calc()`-like functions

### LINKED ISSUE #11682: `calc()` not normalizing
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

PostCSS `8.4.27`
PostCSS Loader `6.2.1`
Webpack `5.88.2`

Also reproduced in Tailwind Play (see below)

**What version of Node.js are you using?**

`16.13.0`

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/7lVcDok0HN

**Describe your issue**

Unfortunately, I come bearing a case where `calc()` value is not properly normalized in an arbitrary value:

`[--foo:calc((704-320)/(1400-782))]`

Which I then extrapolated to more cases to try to narrow down a pattern:

❌ `w-[calc((7-32)/(1400-782))]`
✅ `[--foo:calc((7-3)/(1400-782))]`
❌ `[--foo:calc((7-32)/(1400-782))]`
✅ `[--foo:calc((70-3)/(1400-782))]`
❌ `[--foo:calc((70-32)/(1400-782))]`
✅ `[--foo:calc((704-3)/(1400-782))]`
✅ `[--foo:calc((704-320))]`
❌ `[--foo:calc((704-320)/1)]`
❌ `[--foo:calc((704-320)/(1400-782))]`

For the classes marked with a cross (❌), there is no space around the subtraction operator (`-`) in the first set of parentheses in the generated CSS rule value, causing the `calc()` value to be invalid.

### PR DESCRIPTION
**Pull request by RobinMalfait**
This PR improves the normalisation of `calc()` functions.

In CSS, functions such as `calc()` require spaces around the operators. However, when writing Tailwind CSS classes we can't really use spaces. There are 2 solutions to this problem:

1. You write a `_` instead of a space, which we will convert to a space behind the scenes
2. You don't write any spaces or `_` characters, and you let Tailwind inject the spaces for you

Typically, you would let Tailwind inject the spaces, but we didn't catch all cases. This PR improves that by introducing a mini-parser for handling spaces around operators.

Looking at the examples given in #11682, then the updated result would look like this:

| Input                        | Before                           | After                              |
| ---------------------------- | -------------------------------- | ---------------------------------- |
| `calc((7-32)/(1400-782))`    | `calc((7-32) / (1400 - 782))`    | `calc((7 - 32) / (1400 - 782))`    |
| `calc((7-3)/(1400-782))`     | `calc((7 - 3) / (1400 - 782))`   | `calc((7 - 3) / (1400 - 782))`     |
| `calc((7-32)/(1400-782))`    | `calc((7-32) / (1400 - 782))`    | `calc((7 - 32) / (1400 - 782))`    |
| `calc((70-3)/(1400-782))`    | `calc((70 - 3) / (1400 - 782))`  | `calc((70 - 3) / (1400 - 782))`    |
| `calc((70-32)/(1400-782))`   | `calc((70-32) / (1400 - 782))`   | `calc((70 - 32) / (1400 - 782))`   |
| `calc((704-3)/(1400-782))`   | `calc((704 - 3) / (1400 - 782))` | `calc((704 - 3) / (1400 - 782))`   |
| `calc((704-320))`            | `calc((704 - 320))`              | `calc((704 - 320))`                |
| `calc((704-320)/1)`          | `calc((704-320) / 1)`            | `calc((704 - 320) / 1)`            |
| `calc((704-320)/(1400-782))` | `calc((704-320) / (1400 - 782))` | `calc((704 - 320) / (1400 - 782))` |

Fixes: #11682

### CODE REVIEW

**Review by thecrypticace — APPROVED** [review]

**Comment by mblode** [comment]
3.3.4 caused the following line to break.

Input:
`pb-[max(12px,calc(2*env(safe-area-inset-bottom)))]`

New output:
`padding-bottom: max(12px,calc(2 * env(safe - area - inset - bottom)));`

Old output:
`padding-bottom: max(12px,calc(2 * env(safe-area-inset-bottom)));`

**Comment by Ryan-Maughan** [comment]
Also having issues with 3.3.4. Seems to add spaces for 'min-content' within a minmax function which is invalid.

Input:
`grid-cols-[minmax(min-content,_25%),1fr]`

New output:
`grid-template-columns: minmax(min - content,25%) 1fr`

Old output:
`grid-template-columns: minmax(min-content,25%) 1fr`

**Comment by Serator** [comment]
Hey @RobinMalfait. I too have encountered the problems described above. Tailwind magic is great, but when it's clear and predictable. In this case, not only does this change add problems, it also diverges from regular CSS on an implicit level. Although adding `_` adds pain, it's better than implicit magic.

**Comment by jokull** [comment]
Another data point where this breaks previously working classes:

Input: `grid-cols-[max-content,minmax(max-content,0.5fr)]`
Output: `grid-template-columns: max-content minmax(max - content,0.5fr)`

Note the spacing around the `-` sign.

**Comment by RobinMalfait** [comment]
Hey @mblode, @Ryan-Maughan, @Serator and @jokull 

We introduced a regression here, but this should be fixed by #12283, and is available in the latest release ([3.3.5](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.3.5)). Sorry for the inconvenience!

**Pull request merged**
